var move = {};

move[1] = {name_en: "Pound", type1: "Normal", category: "Physical", pp: 35, power: 40, accuracy: 100}
move[2] = {name_en: "Karate Chop", type1: "Fighting", category: "Physical", pp: 25, power: 50, accuracy: 100}
move[3] = {name_en: "Double Slap", type1: "Normal", category: "Physical", pp: 10, power: 15, accuracy: 85}
move[4] = {name_en: "Comet Punch", type1: "Normal", category: "Physical", pp: 15, power: 18, accuracy: 85}
move[5] = {name_en: "Mega Punch", type1: "Normal", category: "Physical", pp: 20, power: 80, accuracy: 85}
move[6] = {name_en: "Pay Day", type1: "Normal", category: "Physical", pp: 20, power: 40, accuracy: 100}
move[7] = {name_en: "Fire Punch", type1: "Fire", category: "Physical", pp: 15, power: 75, accuracy: 100}
move[8] = {name_en: "Ice Punch", type1: "Ice", category: "Physical", pp: 15, power: 75, accuracy: 100}
move[9] = {name_en: "Thunder Punch", type1: "Electric", category: "Physical", pp: 15, power: 75, accuracy: 100}
move[10] = {name_en: "Scratch", type1: "Normal", category: "Physical", pp: 35, power: 40, accuracy: 100}
move[11] = {name_en: "Vice Grip", type1: "Normal", category: "Physical", pp: 30, power: 55, accuracy: 100}
move[12] = {name_en: "Guillotine", type1: "Normal", category: "Physical", pp: 5, power: "-", accuracy: "-"}
move[13] = {name_en: "Razor Wind", type1: "Normal", category: "Special", pp: 10, power: 80, accuracy: 100}
move[14] = {name_en: "Swords Dance", type1: "Normal", category: "Status", pp: 20, power: "-", accuracy: "-"}
move[15] = {name_en: "Cut", type1: "Normal", category: "Physical", pp: 30, power: 50, accuracy: 95}
move[16] = {name_en: "Gust", type1: "Flying", category: "Special", pp: 35, power: 40, accuracy: 100}
move[17] = {name_en: "Wing Attack", type1: "Flying", category: "Physical", pp: 35, power: 60, accuracy: 100}
move[18] = {name_en: "Whirlwind", type1: "Normal", category: "Status", pp: 20, power: "-", accuracy: "-"}
move[19] = {name_en: "Fly", type1: "Flying", category: "Physical", pp: 15, power: 90, accuracy: 95}
move[20] = {name_en: "Bind", type1: "Normal", category: "Physical", pp: 20, power: 15, accuracy: 85}
move[21] = {name_en: "Slam", type1: "Normal", category: "Physical", pp: 20, power: 80, accuracy: 75}
move[22] = {name_en: "Vine Whip", type1: "Grass", category: "Physical", pp: 25, power: 45, accuracy: 100}
move[23] = {name_en: "Stomp", type1: "Normal", category: "Physical", pp: 20, power: 65, accuracy: 100}
move[24] = {name_en: "Double Kick", type1: "Fighting", category: "Physical", pp: 30, power: 30, accuracy: 100}
move[25] = {name_en: "Mega Kick", type1: "Normal", category: "Physical", pp: 5, power: 120, accuracy: 75}
move[26] = {name_en: "Jump Kick", type1: "Fighting", category: "Physical", pp: 10, power: 100, accuracy: 95}
move[27] = {name_en: "Rolling Kick", type1: "Fighting", category: "Physical", pp: 15, power: 60, accuracy: 85}
move[28] = {name_en: "Sand Attack", type1: "Ground", category: "Status", pp: 15, power: "-", accuracy: 100}
move[29] = {name_en: "Headbutt", type1: "Normal", category: "Physical", pp: 15, power: 70, accuracy: 100}
move[30] = {name_en: "Horn Attack", type1: "Normal", category: "Physical", pp: 25, power: 65, accuracy: 100}
move[31] = {name_en: "Fury Attack", type1: "Normal", category: "Physical", pp: 20, power: 15, accuracy: 85}
move[32] = {name_en: "Horn Drill", type1: "Normal", category: "Physical", pp: 5, power: "-", accuracy: "-"}
move[33] = {name_en: "Tackle", type1: "Normal", category: "Physical", pp: 35, power: 50, accuracy: 100}
move[34] = {name_en: "Body Slam", type1: "Normal", category: "Physical", pp: 15, power: 85, accuracy: 100}
move[35] = {name_en: "Wrap", type1: "Normal", category: "Physical", pp: 20, power: 15, accuracy: 90}
move[36] = {name_en: "Take Down", type1: "Normal", category: "Physical", pp: 20, power: 90, accuracy: 85}
move[37] = {name_en: "Thrash", type1: "Normal", category: "Physical", pp: 10, power: 120, accuracy: 100}
move[38] = {name_en: "Double-Edge", type1: "Normal", category: "Physical", pp: 15, power: 120, accuracy: 100}
move[39] = {name_en: "Tail Whip", type1: "Normal", category: "Status", pp: 30, power: "-", accuracy: 100}
move[40] = {name_en: "Poison Sting", type1: "Poison", category: "Physical", pp: 35, power: 15, accuracy: 100}
move[41] = {name_en: "Twineedle", type1: "Bug", category: "Physical", pp: 20, power: 25, accuracy: 100}
move[42] = {name_en: "Pin Missile", type1: "Bug", category: "Physical", pp: 20, power: 25, accuracy: 95}
move[43] = {name_en: "Leer", type1: "Normal", category: "Status", pp: 30, power: "-", accuracy: 100}
move[44] = {name_en: "Bite", type1: "Dark", category: "Physical", pp: 25, power: 60, accuracy: 100}
move[45] = {name_en: "Growl", type1: "Normal", category: "Status", pp: 40, power: "-", accuracy: 100}
move[46] = {name_en: "Roar", type1: "Normal", category: "Status", pp: 20, power: "-", accuracy: "-"}
move[47] = {name_en: "Sing", type1: "Normal", category: "Status", pp: 15, power: "-", accuracy: 55}
move[48] = {name_en: "Supersonic", type1: "Normal", category: "Status", pp: 20, power: "-", accuracy: 55}
move[49] = {name_en: "Sonic Boom", type1: "Normal", category: "Special", pp: 20, power: , accuracy: 90}
move[50] = {name_en: "Disable", type1: "Normal", category: "Status", pp: 20, power: "-", accuracy: 100}
move[51] = {name_en: "Acid", type1: "Poison", category: "Special", pp: 30, power: 40, accuracy: 100}
move[52] = {name_en: "Ember", type1: "Fire", category: "Special", pp: 25, power: 40, accuracy: 100}
move[53] = {name_en: "Flamethrower", type1: "Fire", category: "Special", pp: 15, power: 90, accuracy: 100}
move[54] = {name_en: "Mist", type1: "Ice", category: "Status", pp: 30, power: "-", accuracy: "-"}
move[55] = {name_en: "Water Gun", type1: "Water", category: "Special", pp: 25, power: 40, accuracy: 100}
move[56] = {name_en: "Hydro Pump", type1: "Water", category: "Special", pp: 5, power: 110, accuracy: 80}
move[57] = {name_en: "Surf", type1: "Water", category: "Special", pp: 15, power: 90, accuracy: 100}
move[58] = {name_en: "Ice Beam", type1: "Ice", category: "Special", pp: 10, power: 90, accuracy: 100}
move[59] = {name_en: "Blizzard", type1: "Ice", category: "Special", pp: 5, power: 110, accuracy: 70}
move[60] = {name_en: "Psybeam", type1: "Psychic", category: "Special", pp: 20, power: 65, accuracy: 100}
move[61] = {name_en: "Bubble Beam", type1: "Water", category: "Special", pp: 20, power: 65, accuracy: 100}
move[62] = {name_en: "Aurora Beam", type1: "Ice", category: "Special", pp: 20, power: 65, accuracy: 100}
move[63] = {name_en: "Hyper Beam", type1: "Normal", category: "Special", pp: 5, power: 150, accuracy: 90}
move[64] = {name_en: "Peck", type1: "Flying", category: "Physical", pp: 35, power: 35, accuracy: 100}
move[65] = {name_en: "Drill Peck", type1: "Flying", category: "Physical", pp: 20, power: 80, accuracy: 100}
move[66] = {name_en: "Submission", type1: "Fighting", category: "Physical", pp: 25, power: 80, accuracy: 80}
move[67] = {name_en: "Low Kick", type1: "Fighting", category: "Physical", pp: 20, power: "-", accuracy: 100}
move[68] = {name_en: "Counter", type1: "Fighting", category: "Physical", pp: 20, power: "-", accuracy: 100}
move[69] = {name_en: "Seismic Toss", type1: "Fighting", category: "Physical", pp: 20, power: "-", accuracy: 100}
move[70] = {name_en: "Strength", type1: "Normal", category: "Physical", pp: 15, power: 80, accuracy: 100}
move[71] = {name_en: "Absorb", type1: "Grass", category: "Special", pp: 25, power: 20, accuracy: 100}
move[72] = {name_en: "Mega Drain", type1: "Grass", category: "Special", pp: 15, power: 40, accuracy: 100}
move[73] = {name_en: "Leech Seed", type1: "Grass", category: "Status", pp: 10, power: "-", accuracy: 90}
move[74] = {name_en: "Growth", type1: "Normal", category: "Status", pp: 20, power: "-", accuracy: "-"}
move[75] = {name_en: "Razor Leaf", type1: "Grass", category: "Physical", pp: 25, power: 55, accuracy: 95}
move[76] = {name_en: "Solar Beam", type1: "Grass", category: "Special", pp: 10, power: 120, accuracy: 100}
move[77] = {name_en: "Poison Powder", type1: "Poison", category: "Status", pp: 35, power: "-", accuracy: 75}
move[78] = {name_en: "Stun Spore", type1: "Grass", category: "Status", pp: 30, power: "-", accuracy: 75}
move[79] = {name_en: "Sleep Powder", type1: "Grass", category: "Status", pp: 15, power: "-", accuracy: 75}
move[80] = {name_en: "Petal Dance", type1: "Grass", category: "Special", pp: 10, power: 120, accuracy: 100}
move[81] = {name_en: "String Shot", type1: "Bug", category: "Status", pp: 40, power: "-", accuracy: 95}
move[82] = {name_en: "Dragon Rage", type1: "Dragon", category: "Special", pp: 10, power: , accuracy: 100}
move[83] = {name_en: "Fire Spin", type1: "Fire", category: "Special", pp: 15, power: 35, accuracy: 85}
move[84] = {name_en: "Thunder Shock", type1: "Electric", category: "Special", pp: 30, power: 40, accuracy: 100}
move[85] = {name_en: "Thunderbolt", type1: "Electric", category: "Special", pp: 15, power: 90, accuracy: 100}
move[86] = {name_en: "Thunder Wave", type1: "Electric", category: "Status", pp: 20, power: "-", accuracy: 100}
move[87] = {name_en: "Thunder", type1: "Electric", category: "Special", pp: 10, power: 110, accuracy: 70}
move[88] = {name_en: "Rock Throw", type1: "Rock", category: "Physical", pp: 15, power: 50, accuracy: 90}
move[89] = {name_en: "Earthquake", type1: "Ground", category: "Physical", pp: 10, power: 100, accuracy: 100}
move[90] = {name_en: "Fissure", type1: "Ground", category: "Physical", pp: 5, power: "-", accuracy: "-"}
move[91] = {name_en: "Dig", type1: "Ground", category: "Physical", pp: 10, power: 80, accuracy: 100}
move[92] = {name_en: "Toxic", type1: "Poison", category: "Status", pp: 10, power: "-", accuracy: 90}
move[93] = {name_en: "Confusion", type1: "Psychic", category: "Special", pp: 25, power: 50, accuracy: 100}
move[94] = {name_en: "Psychic", type1: "Psychic", category: "Special", pp: 10, power: 90, accuracy: 100}
move[95] = {name_en: "Hypnosis", type1: "Psychic", category: "Status", pp: 20, power: "-", accuracy: 60}
move[96] = {name_en: "Meditate", type1: "Psychic", category: "Status", pp: 40, power: "-", accuracy: "-"}
move[97] = {name_en: "Agility", type1: "Psychic", category: "Status", pp: 30, power: "-", accuracy: "-"}
move[98] = {name_en: "Quick Attack", type1: "Normal", category: "Physical", pp: 30, power: 40, accuracy: 100}
move[99] = {name_en: "Rage", type1: "Normal", category: "Physical", pp: 20, power: 20, accuracy: 100}
move[100] = {name_en: "Teleport", type1: "Psychic", category: "Status", pp: 20, power: "-", accuracy: "-"}
move[101] = {name_en: "Night Shade", type1: "Ghost", category: "Special", pp: 15, power: "-", accuracy: 100}
move[102] = {name_en: "Mimic", type1: "Normal", category: "Status", pp: 10, power: "-", accuracy: 100}
move[103] = {name_en: "Screech", type1: "Normal", category: "Status", pp: 40, power: "-", accuracy: 85}
move[104] = {name_en: "Double Team", type1: "Normal", category: "Status", pp: 15, power: "-", accuracy: "-"}
move[105] = {name_en: "Recover", type1: "Normal", category: "Status", pp: 10, power: "-", accuracy: "-"}
move[106] = {name_en: "Harden", type1: "Normal", category: "Status", pp: 30, power: "-", accuracy: "-"}
move[107] = {name_en: "Minimize", type1: "Normal", category: "Status", pp: 10, power: "-", accuracy: "-"}
move[108] = {name_en: "Smokescreen", type1: "Normal", category: "Status", pp: 20, power: "-", accuracy: 100}
move[109] = {name_en: "Confuse Ray", type1: "Ghost", category: "Status", pp: 10, power: "-", accuracy: 100}
move[110] = {name_en: "Withdraw", type1: "Water", category: "Status", pp: 40, power: "-", accuracy: "-"}
move[111] = {name_en: "Defense Curl", type1: "Normal", category: "Status", pp: 40, power: "-", accuracy: "-"}
move[112] = {name_en: "Barrier", type1: "Psychic", category: "Status", pp: 20, power: "-", accuracy: "-"}
move[113] = {name_en: "Light Screen", type1: "Psychic", category: "Status", pp: 30, power: "-", accuracy: "-"}
move[114] = {name_en: "Haze", type1: "Ice", category: "Status", pp: 30, power: "-", accuracy: "-"}
move[115] = {name_en: "Reflect", type1: "Psychic", category: "Status", pp: 20, power: "-", accuracy: "-"}
move[116] = {name_en: "Focus Energy", type1: "Normal", category: "Status", pp: 30, power: "-", accuracy: "-"}
move[117] = {name_en: "Bide", type1: "Normal", category: "Physical", pp: 10, power: "-", accuracy: 100}
move[118] = {name_en: "Metronome", type1: "Normal", category: "Status", pp: 10, power: "-", accuracy: "-"}
move[119] = {name_en: "Mirror Move", type1: "Flying", category: "Status", pp: 20, power: "-", accuracy: "-"}
move[120] = {name_en: "Self-Destruct", type1: "Normal", category: "Physical", pp: 5, power: 200, accuracy: 100}
move[121] = {name_en: "Egg Bomb", type1: "Normal", category: "Physical", pp: 10, power: 100, accuracy: 75}
move[122] = {name_en: "Lick", type1: "Ghost", category: "Physical", pp: 30, power: 30, accuracy: 100}
move[123] = {name_en: "Smog", type1: "Poison", category: "Special", pp: 20, power: 30, accuracy: 70}
move[124] = {name_en: "Sludge", type1: "Poison", category: "Special", pp: 20, power: 65, accuracy: 100}
move[125] = {name_en: "Bone Club", type1: "Ground", category: "Physical", pp: 20, power: 65, accuracy: 85}
move[126] = {name_en: "Fire Blast", type1: "Fire", category: "Special", pp: 5, power: 110, accuracy: 85}
move[127] = {name_en: "Waterfall", type1: "Water", category: "Physical", pp: 15, power: 80, accuracy: 100}
move[128] = {name_en: "Clamp", type1: "Water", category: "Physical", pp: 15, power: 35, accuracy: 85}
move[129] = {name_en: "Swift", type1: "Normal", category: "Special", pp: 20, power: 60, accuracy: "-"}
move[130] = {name_en: "Skull Bash", type1: "Normal", category: "Physical", pp: 10, power: 130, accuracy: 100}
move[131] = {name_en: "Spike Cannon", type1: "Normal", category: "Physical", pp: 15, power: 20, accuracy: 100}
move[132] = {name_en: "Constrict", type1: "Normal", category: "Physical", pp: 35, power: 10, accuracy: 100}
move[133] = {name_en: "Amnesia", type1: "Psychic", category: "Status", pp: 20, power: "-", accuracy: "-"}
move[134] = {name_en: "Kinesis", type1: "Psychic", category: "Status", pp: 15, power: "-", accuracy: 80}
move[135] = {name_en: "Soft-Boiled", type1: "Normal", category: "Status", pp: 10, power: "-", accuracy: "-"}
move[136] = {name_en: "High Jump Kick", type1: "Fighting", category: "Physical", pp: 10, power: 130, accuracy: 90}
move[137] = {name_en: "Glare", type1: "Normal", category: "Status", pp: 30, power: "-", accuracy: 100}
move[138] = {name_en: "Dream Eater", type1: "Psychic", category: "Special", pp: 15, power: 100, accuracy: 100}
move[139] = {name_en: "Poison Gas", type1: "Poison", category: "Status", pp: 40, power: "-", accuracy: 90}
move[140] = {name_en: "Barrage", type1: "Normal", category: "Physical", pp: 20, power: 15, accuracy: 85}
move[141] = {name_en: "Leech Life", type1: "Bug", category: "Physical", pp: 15, power: 20, accuracy: 100}
move[142] = {name_en: "Lovely Kiss", type1: "Normal", category: "Status", pp: 10, power: "-", accuracy: 75}
move[143] = {name_en: "Sky Attack", type1: "Flying", category: "Physical", pp: 5, power: 140, accuracy: 90}
move[144] = {name_en: "Transform", type1: "Normal", category: "Status", pp: 10, power: "-", accuracy: "-"}
move[145] = {name_en: "Bubble", type1: "Water", category: "Special", pp: 30, power: 40, accuracy: 100}
move[146] = {name_en: "Dizzy Punch", type1: "Normal", category: "Physical", pp: 10, power: 70, accuracy: 100}
move[147] = {name_en: "Spore", type1: "Grass", category: "Status", pp: 15, power: "-", accuracy: 100}
move[148] = {name_en: "Flash", type1: "Normal", category: "Status", pp: 20, power: "-", accuracy: 100}
move[149] = {name_en: "Psywave", type1: "Psychic", category: "Special", pp: 15, power: "-", accuracy: 100}
move[150] = {name_en: "Splash", type1: "Normal", category: "Status", pp: 40, power: "-", accuracy: "-"}
move[151] = {name_en: "Acid Armor", type1: "Poison", category: "Status", pp: 20, power: "-", accuracy: "-"}
move[152] = {name_en: "Crabhammer", type1: "Water", category: "Physical", pp: 10, power: 100, accuracy: 90}
move[153] = {name_en: "Explosion", type1: "Normal", category: "Physical", pp: 5, power: 250, accuracy: 100}
move[154] = {name_en: "Fury Swipes", type1: "Normal", category: "Physical", pp: 15, power: 18, accuracy: 80}
move[155] = {name_en: "Bonemerang", type1: "Ground", category: "Physical", pp: 10, power: 50, accuracy: 90}
move[156] = {name_en: "Rest", type1: "Psychic", category: "Status", pp: 10, power: "-", accuracy: "-"}
move[157] = {name_en: "Rock Slide", type1: "Rock", category: "Physical", pp: 10, power: 75, accuracy: 90}
move[158] = {name_en: "Hyper Fang", type1: "Normal", category: "Physical", pp: 15, power: 80, accuracy: 90}
move[159] = {name_en: "Sharpen", type1: "Normal", category: "Status", pp: 30, power: "-", accuracy: "-"}
move[160] = {name_en: "Conversion", type1: "Normal", category: "Status", pp: 30, power: "-", accuracy: "-"}
move[161] = {name_en: "Tri Attack", type1: "Normal", category: "Special", pp: 10, power: 80, accuracy: 100}
move[162] = {name_en: "Super Fang", type1: "Normal", category: "Physical", pp: 10, power: "-", accuracy: 90}
move[163] = {name_en: "Slash", type1: "Normal", category: "Physical", pp: 20, power: 70, accuracy: 100}
move[164] = {name_en: "Substitute", type1: "Normal", category: "Status", pp: 10, power: "-", accuracy: "-"}
move[165] = {name_en: "Struggle", type1: "Normal", category: "Physical", pp: 1, power: 50, accuracy: "-"}
move[166] = {name_en: "Sketch", type1: "Normal", category: "Status", pp: 1, power: "-", accuracy: "-"}
move[167] = {name_en: "Triple Kick", type1: "Fighting", category: "Physical", pp: 10, power: 10, accuracy: 90}
move[168] = {name_en: "Thief", type1: "Dark", category: "Physical", pp: 25, power: 60, accuracy: 100}
move[169] = {name_en: "Spider Web", type1: "Bug", category: "Status", pp: 10, power: "-", accuracy: 100}
move[170] = {name_en: "Mind Reader", type1: "Normal", category: "Status", pp: 5, power: "-", accuracy: 100}
move[171] = {name_en: "Nightmare", type1: "Ghost", category: "Status", pp: 15, power: "-", accuracy: 100}
move[172] = {name_en: "Flame Wheel", type1: "Fire", category: "Physical", pp: 25, power: 60, accuracy: 100}
move[173] = {name_en: "Snore", type1: "Normal", category: "Special", pp: 15, power: 50, accuracy: 100}
move[174] = {name_en: "Curse", type1: "Ghost", category: "Status", pp: 10, power: "-", accuracy: "-"}
move[175] = {name_en: "Flail", type1: "Normal", category: "Physical", pp: 15, power: "-", accuracy: 100}
move[176] = {name_en: "Conversion 2", type1: "Normal", category: "Status", pp: 30, power: "-", accuracy: 100}
move[177] = {name_en: "Aeroblast", type1: "Flying", category: "Special", pp: 5, power: 100, accuracy: 95}
move[178] = {name_en: "Cotton Spore", type1: "Grass", category: "Status", pp: 40, power: "-", accuracy: 100}
move[179] = {name_en: "Reversal", type1: "Fighting", category: "Physical", pp: 15, power: "-", accuracy: 100}
move[180] = {name_en: "Spite", type1: "Ghost", category: "Status", pp: 10, power: "-", accuracy: 100}
move[181] = {name_en: "Powder Snow", type1: "Ice", category: "Special", pp: 25, power: 40, accuracy: 100}
move[182] = {name_en: "Protect", type1: "Normal", category: "Status", pp: 10, power: "-", accuracy: "-"}
move[183] = {name_en: "Mach Punch", type1: "Fighting", category: "Physical", pp: 30, power: 40, accuracy: 100}
move[184] = {name_en: "Scary Face", type1: "Normal", category: "Status", pp: 10, power: "-", accuracy: 100}
move[185] = {name_en: "Feint Attack", type1: "Dark", category: "Physical", pp: 20, power: 60, accuracy: "-"}
move[186] = {name_en: "Sweet Kiss", type1: "Fairy", category: "Status", pp: 10, power: "-", accuracy: 75}
move[187] = {name_en: "Belly Drum", type1: "Normal", category: "Status", pp: 10, power: "-", accuracy: "-"}
move[188] = {name_en: "Sludge Bomb", type1: "Poison", category: "Special", pp: 10, power: 90, accuracy: 100}
move[189] = {name_en: "Mud-Slap", type1: "Ground", category: "Special", pp: 10, power: 20, accuracy: 100}
move[190] = {name_en: "Octazooka", type1: "Water", category: "Special", pp: 10, power: 65, accuracy: 85}
move[191] = {name_en: "Spikes", type1: "Ground", category: "Status", pp: 20, power: "-", accuracy: "-"}
move[192] = {name_en: "Zap Cannon", type1: "Electric", category: "Special", pp: 5, power: 120, accuracy: 50}
move[193] = {name_en: "Foresight", type1: "Normal", category: "Status", pp: 40, power: "-", accuracy: 100}
move[194] = {name_en: "Destiny Bond", type1: "Ghost", category: "Status", pp: 5, power: "-", accuracy: "-"}
move[195] = {name_en: "Perish Song", type1: "Normal", category: "Status", pp: 5, power: "-", accuracy: "-"}
move[196] = {name_en: "Icy Wind", type1: "Ice", category: "Special", pp: 15, power: 55, accuracy: 95}
move[197] = {name_en: "Detect", type1: "Fighting", category: "Status", pp: 5, power: "-", accuracy: "-"}
move[198] = {name_en: "Bone Rush", type1: "Ground", category: "Physical", pp: 10, power: 25, accuracy: 90}
move[199] = {name_en: "Lock-On", type1: "Normal", category: "Status", pp: 5, power: "-", accuracy: 100}
move[200] = {name_en: "Outrage", type1: "Dragon", category: "Physical", pp: 10, power: 120, accuracy: 100}
move[201] = {name_en: "Sandstorm", type1: "Rock", category: "Status", pp: 10, power: "-", accuracy: "-"}
move[202] = {name_en: "Giga Drain", type1: "Grass", category: "Special", pp: 10, power: 75, accuracy: 100}
move[203] = {name_en: "Endure", type1: "Normal", category: "Status", pp: 10, power: "-", accuracy: "-"}
move[204] = {name_en: "Charm", type1: "Fairy", category: "Status", pp: 20, power: "-", accuracy: 100}
move[205] = {name_en: "Rollout", type1: "Rock", category: "Physical", pp: 20, power: 30, accuracy: 90}
move[206] = {name_en: "False Swipe", type1: "Normal", category: "Physical", pp: 40, power: 40, accuracy: 100}
move[207] = {name_en: "Swagger", type1: "Normal", category: "Status", pp: 15, power: "-", accuracy: 90}
move[208] = {name_en: "Milk Drink", type1: "Normal", category: "Status", pp: 10, power: "-", accuracy: "-"}
move[209] = {name_en: "Spark", type1: "Electric", category: "Physical", pp: 20, power: 65, accuracy: 100}
move[210] = {name_en: "Fury Cutter", type1: "Bug", category: "Physical", pp: 20, power: 40, accuracy: 95}
move[211] = {name_en: "Steel Wing", type1: "Steel", category: "Physical", pp: 25, power: 70, accuracy: 90}
move[212] = {name_en: "Mean Look", type1: "Normal", category: "Status", pp: 5, power: "-", accuracy: 100}
move[213] = {name_en: "Attract", type1: "Normal", category: "Status", pp: 15, power: "-", accuracy: 100}
move[214] = {name_en: "Sleep Talk", type1: "Normal", category: "Status", pp: 10, power: "-", accuracy: "-"}
move[215] = {name_en: "Heal Bell", type1: "Normal", category: "Status", pp: 5, power: "-", accuracy: "-"}
move[216] = {name_en: "Return", type1: "Normal", category: "Physical", pp: 20, power: "-", accuracy: 100}
move[217] = {name_en: "Present", type1: "Normal", category: "Physical", pp: 15, power: "-", accuracy: 90}
move[218] = {name_en: "Frustration", type1: "Normal", category: "Physical", pp: 20, power: "-", accuracy: 100}
move[219] = {name_en: "Safeguard", type1: "Normal", category: "Status", pp: 25, power: "-", accuracy: "-"}
move[220] = {name_en: "Pain Split", type1: "Normal", category: "Status", pp: 20, power: "-", accuracy: 100}
move[221] = {name_en: "Sacred Fire", type1: "Fire", category: "Physical", pp: 5, power: 100, accuracy: 95}
move[222] = {name_en: "Magnitude", type1: "Ground", category: "Physical", pp: 30, power: "-", accuracy: 100}
move[223] = {name_en: "Dynamic Punch", type1: "Fighting", category: "Physical", pp: 5, power: 100, accuracy: 50}
move[224] = {name_en: "Megahorn", type1: "Bug", category: "Physical", pp: 10, power: 120, accuracy: 85}
move[225] = {name_en: "Dragon Breath", type1: "Dragon", category: "Special", pp: 20, power: 60, accuracy: 100}
move[226] = {name_en: "Baton Pass", type1: "Normal", category: "Status", pp: 40, power: "-", accuracy: "-"}
move[227] = {name_en: "Encore", type1: "Normal", category: "Status", pp: 5, power: "-", accuracy: 100}
move[228] = {name_en: "Pursuit", type1: "Dark", category: "Physical", pp: 20, power: 40, accuracy: 100}
move[229] = {name_en: "Rapid Spin", type1: "Normal", category: "Physical", pp: 40, power: 20, accuracy: 100}
move[230] = {name_en: "Sweet Scent", type1: "Normal", category: "Status", pp: 20, power: "-", accuracy: 100}
move[231] = {name_en: "Iron Tail", type1: "Steel", category: "Physical", pp: 15, power: 100, accuracy: 75}
move[232] = {name_en: "Metal Claw", type1: "Steel", category: "Physical", pp: 35, power: 50, accuracy: 95}
move[233] = {name_en: "Vital Throw", type1: "Fighting", category: "Physical", pp: 10, power: 70, accuracy: "-"}
move[234] = {name_en: "Morning Sun", type1: "Normal", category: "Status", pp: 5, power: "-", accuracy: "-"}
move[235] = {name_en: "Synthesis", type1: "Grass", category: "Status", pp: 5, power: "-", accuracy: "-"}
move[236] = {name_en: "Moonlight", type1: "Fairy", category: "Status", pp: 5, power: "-", accuracy: "-"}
move[237] = {name_en: "Hidden Power", type1: "Normal", category: "Special", pp: 15, power: 60, accuracy: 100}
move[238] = {name_en: "Cross Chop", type1: "Fighting", category: "Physical", pp: 5, power: 100, accuracy: 80}
move[239] = {name_en: "Twister", type1: "Dragon", category: "Special", pp: 20, power: 40, accuracy: 100}
move[240] = {name_en: "Rain Dance", type1: "Water", category: "Status", pp: 5, power: "-", accuracy: "-"}
move[241] = {name_en: "Sunny Day", type1: "Fire", category: "Status", pp: 5, power: "-", accuracy: "-"}
move[242] = {name_en: "Crunch", type1: "Dark", category: "Physical", pp: 15, power: 80, accuracy: 100}
move[243] = {name_en: "Mirror Coat", type1: "Psychic", category: "Special", pp: 20, power: "-", accuracy: 100}
move[244] = {name_en: "Psych Up", type1: "Normal", category: "Status", pp: 10, power: "-", accuracy: "-"}
move[245] = {name_en: "Extreme Speed", type1: "Normal", category: "Physical", pp: 5, power: 80, accuracy: 100}
move[246] = {name_en: "Ancient Power", type1: "Rock", category: "Special", pp: 5, power: 60, accuracy: 100}
move[247] = {name_en: "Shadow Ball", type1: "Ghost", category: "Special", pp: 15, power: 80, accuracy: 100}
move[248] = {name_en: "Future Sight", type1: "Psychic", category: "Special", pp: 10, power: 120, accuracy: 100}
move[249] = {name_en: "Rock Smash", type1: "Fighting", category: "Physical", pp: 15, power: 40, accuracy: 100}
move[250] = {name_en: "Whirlpool", type1: "Water", category: "Special", pp: 15, power: 35, accuracy: 85}
move[251] = {name_en: "Beat Up", type1: "Dark", category: "Physical", pp: 10, power: "-", accuracy: 100}
move[252] = {name_en: "Fake Out", type1: "Normal", category: "Physical", pp: 10, power: 40, accuracy: 100}
move[253] = {name_en: "Uproar", type1: "Normal", category: "Special", pp: 10, power: 90, accuracy: 100}
move[254] = {name_en: "Stockpile", type1: "Normal", category: "Status", pp: 20, power: "-", accuracy: "-"}
move[255] = {name_en: "Spit Up", type1: "Normal", category: "Special", pp: 10, power: "-", accuracy: 100}
move[256] = {name_en: "Swallow", type1: "Normal", category: "Status", pp: 10, power: "-", accuracy: "-"}
move[257] = {name_en: "Heat Wave", type1: "Fire", category: "Special", pp: 10, power: 95, accuracy: 90}
move[258] = {name_en: "Hail", type1: "Ice", category: "Status", pp: 10, power: "-", accuracy: "-"}
move[259] = {name_en: "Torment", type1: "Dark", category: "Status", pp: 15, power: "-", accuracy: 100}
move[260] = {name_en: "Flatter", type1: "Dark", category: "Status", pp: 15, power: "-", accuracy: 100}
move[261] = {name_en: "Will-O-Wisp", type1: "Fire", category: "Status", pp: 15, power: "-", accuracy: 85}
move[262] = {name_en: "Memento", type1: "Dark", category: "Status", pp: 10, power: "-", accuracy: 100}
move[263] = {name_en: "Facade", type1: "Normal", category: "Physical", pp: 20, power: 70, accuracy: 100}
move[264] = {name_en: "Focus Punch", type1: "Fighting", category: "Physical", pp: 20, power: 150, accuracy: 100}
move[265] = {name_en: "Smelling Salts", type1: "Normal", category: "Physical", pp: 10, power: 70, accuracy: 100}
move[266] = {name_en: "Follow Me", type1: "Normal", category: "Status", pp: 20, power: "-", accuracy: 100}
move[267] = {name_en: "Nature Power", type1: "Normal", category: "Status", pp: 20, power: "-", accuracy: "-"}
move[268] = {name_en: "Charge", type1: "Electric", category: "Status", pp: 20, power: "-", accuracy: "-"}
move[269] = {name_en: "Taunt", type1: "Dark", category: "Status", pp: 20, power: "-", accuracy: 100}
move[270] = {name_en: "Helping Hand", type1: "Normal", category: "Status", pp: 20, power: "-", accuracy: "-"}
move[271] = {name_en: "Trick", type1: "Psychic", category: "Status", pp: 10, power: "-", accuracy: 100}
move[272] = {name_en: "Role Play", type1: "Psychic", category: "Status", pp: 10, power: "-", accuracy: "-"}
move[273] = {name_en: "Wish", type1: "Normal", category: "Status", pp: 10, power: "-", accuracy: "-"}
move[274] = {name_en: "Assist", type1: "Normal", category: "Status", pp: 20, power: "-", accuracy: "-"}
move[275] = {name_en: "Ingrain", type1: "Grass", category: "Status", pp: 20, power: "-", accuracy: "-"}
move[276] = {name_en: "Superpower", type1: "Fighting", category: "Physical", pp: 5, power: 120, accuracy: 100}
move[277] = {name_en: "Magic Coat", type1: "Psychic", category: "Status", pp: 15, power: "-", accuracy: "-"}
move[278] = {name_en: "Recycle", type1: "Normal", category: "Status", pp: 10, power: "-", accuracy: 100}
move[279] = {name_en: "Revenge", type1: "Fighting", category: "Physical", pp: 10, power: 60, accuracy: 100}
move[280] = {name_en: "Brick Break", type1: "Fighting", category: "Physical", pp: 15, power: 75, accuracy: 100}
move[281] = {name_en: "Yawn", type1: "Normal", category: "Status", pp: 10, power: "-", accuracy: 100}
move[282] = {name_en: "Knock Off", type1: "Dark", category: "Physical", pp: 20, power: 65, accuracy: 100}
move[283] = {name_en: "Endeavor", type1: "Normal", category: "Physical", pp: 5, power: "-", accuracy: 100}
move[284] = {name_en: "Eruption", type1: "Fire", category: "Special", pp: 5, power: "-", accuracy: 100}
move[285] = {name_en: "Skill Swap", type1: "Psychic", category: "Status", pp: 10, power: "-", accuracy: 100}
move[286] = {name_en: "Imprison", type1: "Psychic", category: "Status", pp: 10, power: "-", accuracy: 100}
move[287] = {name_en: "Refresh", type1: "Normal", category: "Status", pp: 20, power: "-", accuracy: 100}
move[288] = {name_en: "Grudge", type1: "Ghost", category: "Status", pp: 5, power: "-", accuracy: 100}
move[289] = {name_en: "Snatch", type1: "Dark", category: "Status", pp: 10, power: "-", accuracy: 100}
move[290] = {name_en: "Secret Power", type1: "Normal", category: "Physical", pp: 20, power: 70, accuracy: 100}
move[291] = {name_en: "Dive", type1: "Water", category: "Physical", pp: 10, power: 80, accuracy: 100}
move[292] = {name_en: "Arm Thrust", type1: "Fighting", category: "Physical", pp: 20, power: 15, accuracy: 100}
move[293] = {name_en: "Camouflage", type1: "Normal", category: "Status", pp: 20, power: "-", accuracy: 100}
move[294] = {name_en: "Tail Glow", type1: "Bug", category: "Status", pp: 20, power: "-", accuracy: 100}
move[295] = {name_en: "Luster Purge", type1: "Psychic", category: "Special", pp: 5, power: 70, accuracy: 100}
move[296] = {name_en: "Mist Ball", type1: "Psychic", category: "Special", pp: 5, power: 70, accuracy: 100}
move[297] = {name_en: "Feather Dance", type1: "Flying", category: "Status", pp: 15, power: "-", accuracy: 100}
move[298] = {name_en: "Teeter Dance", type1: "Normal", category: "Status", pp: 20, power: "-", accuracy: 100}
move[299] = {name_en: "Blaze Kick", type1: "Fire", category: "Physical", pp: 10, power: 85, accuracy: 90}
move[300] = {name_en: "Mud Sport", type1: "Ground", category: "Status", pp: 15, power: "-", accuracy: 100}
move[301] = {name_en: "Ice Ball", type1: "Ice", category: "Physical", pp: 20, power: 30, accuracy: 90}
move[302] = {name_en: "Needle Arm", type1: "Grass", category: "Physical", pp: 15, power: 60, accuracy: 100}
move[303] = {name_en: "Slack Off", type1: "Normal", category: "Status", pp: 10, power: "-", accuracy: 100}
move[304] = {name_en: "Hyper Voice", type1: "Normal", category: "Special", pp: 10, power: 90, accuracy: 100}
move[305] = {name_en: "Poison Fang", type1: "Poison", category: "Physical", pp: 15, power: 50, accuracy: 100}
move[306] = {name_en: "Crush Claw", type1: "Normal", category: "Physical", pp: 10, power: 75, accuracy: 95}
move[307] = {name_en: "Blast Burn", type1: "Fire", category: "Special", pp: 5, power: 150, accuracy: 90}
move[308] = {name_en: "Hydro Cannon", type1: "Water", category: "Special", pp: 5, power: 150, accuracy: 90}
move[309] = {name_en: "Meteor Mash", type1: "Steel", category: "Physical", pp: 10, power: 90, accuracy: 90}
move[310] = {name_en: "Astonish", type1: "Ghost", category: "Physical", pp: 15, power: 30, accuracy: 100}
move[311] = {name_en: "Weather Ball", type1: "Normal", category: "Special", pp: 10, power: 50, accuracy: 100}
move[312] = {name_en: "Aromatherapy", type1: "Grass", category: "Status", pp: 5, power: "-", accuracy: "-"}
move[313] = {name_en: "Fake Tears", type1: "Dark", category: "Status", pp: 20, power: "-", accuracy: 100}
move[314] = {name_en: "Air Cutter", type1: "Flying", category: "Special", pp: 25, power: 60, accuracy: 95}
move[315] = {name_en: "Overheat", type1: "Fire", category: "Special", pp: 5, power: 130, accuracy: 90}
move[316] = {name_en: "Odor Sleuth", type1: "Normal", category: "Status", pp: 40, power: "-", accuracy: 100}
move[317] = {name_en: "Rock Tomb", type1: "Rock", category: "Physical", pp: 15, power: 60, accuracy: 95}
move[318] = {name_en: "Silver Wind", type1: "Bug", category: "Special", pp: 5, power: 60, accuracy: 100}
move[319] = {name_en: "Metal Sound", type1: "Steel", category: "Status", pp: 40, power: "-", accuracy: 85}
move[320] = {name_en: "Grass Whistle", type1: "Grass", category: "Status", pp: 15, power: "-", accuracy: 55}
move[321] = {name_en: "Tickle", type1: "Normal", category: "Status", pp: 20, power: "-", accuracy: 100}
move[322] = {name_en: "Cosmic Power", type1: "Psychic", category: "Status", pp: 20, power: "-", accuracy: "-"}
move[323] = {name_en: "Water Spout", type1: "Water", category: "Special", pp: 5, power: "-", accuracy: 100}
move[324] = {name_en: "Signal Beam", type1: "Bug", category: "Special", pp: 15, power: 75, accuracy: 100}
move[325] = {name_en: "Shadow Punch", type1: "Ghost", category: "Physical", pp: 20, power: 60, accuracy: "-"}
move[326] = {name_en: "Extrasensory", type1: "Psychic", category: "Special", pp: 20, power: 80, accuracy: 100}
move[327] = {name_en: "Sky Uppercut", type1: "Fighting", category: "Physical", pp: 15, power: 85, accuracy: 90}
move[328] = {name_en: "Sand Tomb", type1: "Ground", category: "Physical", pp: 15, power: 35, accuracy: 85}
move[329] = {name_en: "Sheer Cold", type1: "Ice", category: "Special", pp: 5, power: "-", accuracy: "-"}
move[330] = {name_en: "Muddy Water", type1: "Water", category: "Special", pp: 10, power: 90, accuracy: 85}
move[331] = {name_en: "Bullet Seed", type1: "Grass", category: "Physical", pp: 30, power: 25, accuracy: 100}
move[332] = {name_en: "Aerial Ace", type1: "Flying", category: "Physical", pp: 20, power: 60, accuracy: "-"}
move[333] = {name_en: "Icicle Spear", type1: "Ice", category: "Physical", pp: 30, power: 25, accuracy: 100}
move[334] = {name_en: "Iron Defense", type1: "Steel", category: "Status", pp: 15, power: "-", accuracy: "-"}
move[335] = {name_en: "Block", type1: "Normal", category: "Status", pp: 5, power: "-", accuracy: 100}
move[336] = {name_en: "Howl", type1: "Normal", category: "Status", pp: 40, power: "-", accuracy: "-"}
move[337] = {name_en: "Dragon Claw", type1: "Dragon", category: "Physical", pp: 15, power: 80, accuracy: 100}
move[338] = {name_en: "Frenzy Plant", type1: "Grass", category: "Special", pp: 5, power: 150, accuracy: 90}
move[339] = {name_en: "Bulk Up", type1: "Fighting", category: "Status", pp: 20, power: "-", accuracy: "-"}
move[340] = {name_en: "Bounce", type1: "Flying", category: "Physical", pp: 5, power: 85, accuracy: 85}
move[341] = {name_en: "Mud Shot", type1: "Ground", category: "Special", pp: 15, power: 55, accuracy: 95}
move[342] = {name_en: "Poison Tail", type1: "Poison", category: "Physical", pp: 25, power: 50, accuracy: 100}
move[343] = {name_en: "Covet", type1: "Normal", category: "Physical", pp: 25, power: 60, accuracy: 100}
move[344] = {name_en: "Volt Tackle", type1: "Electric", category: "Physical", pp: 15, power: 120, accuracy: 100}
move[345] = {name_en: "Magical Leaf", type1: "Grass", category: "Special", pp: 20, power: 60, accuracy: "-"}
move[346] = {name_en: "Water Sport", type1: "Water", category: "Status", pp: 15, power: "-", accuracy: 100}
move[347] = {name_en: "Calm Mind", type1: "Psychic", category: "Status", pp: 20, power: "-", accuracy: "-"}
move[348] = {name_en: "Leaf Blade", type1: "Grass", category: "Physical", pp: 15, power: 90, accuracy: 100}
move[349] = {name_en: "Dragon Dance", type1: "Dragon", category: "Status", pp: 20, power: "-", accuracy: "-"}
move[350] = {name_en: "Rock Blast", type1: "Rock", category: "Physical", pp: 10, power: 25, accuracy: 90}
move[351] = {name_en: "Shock Wave", type1: "Electric", category: "Special", pp: 20, power: 60, accuracy: "-"}
move[352] = {name_en: "Water Pulse", type1: "Water", category: "Special", pp: 20, power: 60, accuracy: 100}
move[353] = {name_en: "Doom Desire", type1: "Steel", category: "Special", pp: 5, power: 140, accuracy: 100}
move[354] = {name_en: "Psycho Boost", type1: "Psychic", category: "Special", pp: 5, power: 140, accuracy: 90}
move[355] = {name_en: "Roost", type1: "Flying", category: "Status", pp: 10, power: "-", accuracy: "-"}
move[356] = {name_en: "Gravity", type1: "Psychic", category: "Status", pp: 5, power: "-", accuracy: "-"}
move[357] = {name_en: "Miracle Eye", type1: "Psychic", category: "Status", pp: 40, power: "-", accuracy: "-"}
move[358] = {name_en: "Wake-Up Slap", type1: "Fighting", category: "Physical", pp: 10, power: 70, accuracy: 100}
move[359] = {name_en: "Hammer Arm", type1: "Fighting", category: "Physical", pp: 10, power: 100, accuracy: 90}
move[360] = {name_en: "Gyro Ball", type1: "Steel", category: "Physical", pp: 5, power: "-", accuracy: 100}
move[361] = {name_en: "Healing Wish", type1: "Psychic", category: "Status", pp: 10, power: "-", accuracy: "-"}
move[362] = {name_en: "Brine", type1: "Water", category: "Special", pp: 10, power: 65, accuracy: 100}
move[363] = {name_en: "Natural Gift", type1: "Normal", category: "Physical", pp: 15, power: "-", accuracy: 100}
move[364] = {name_en: "Feint", type1: "Normal", category: "Physical", pp: 10, power: 30, accuracy: 100}
move[365] = {name_en: "Pluck", type1: "Flying", category: "Physical", pp: 20, power: 60, accuracy: 100}
move[366] = {name_en: "Tailwind", type1: "Flying", category: "Status", pp: 15, power: "-", accuracy: "-"}
move[367] = {name_en: "Acupressure", type1: "Normal", category: "Status", pp: 30, power: "-", accuracy: "-"}
move[368] = {name_en: "Metal Burst", type1: "Steel", category: "Physical", pp: 10, power: "-", accuracy: 100}
move[369] = {name_en: "U-turn", type1: "Bug", category: "Physical", pp: 20, power: 70, accuracy: 100}
move[370] = {name_en: "Close Combat", type1: "Fighting", category: "Physical", pp: 5, power: 120, accuracy: 100}
move[371] = {name_en: "Payback", type1: "Dark", category: "Physical", pp: 10, power: 50, accuracy: 100}
move[372] = {name_en: "Assurance", type1: "Dark", category: "Physical", pp: 10, power: 60, accuracy: 100}
move[373] = {name_en: "Embargo", type1: "Dark", category: "Status", pp: 15, power: "-", accuracy: 100}
move[374] = {name_en: "Fling", type1: "Dark", category: "Physical", pp: 10, power: "-", accuracy: 100}
move[375] = {name_en: "Psycho Shift", type1: "Psychic", category: "Status", pp: 10, power: "-", accuracy: 100}
move[376] = {name_en: "Trump Card", type1: "Normal", category: "Special", pp: 5, power: "-", accuracy: "-"}
move[377] = {name_en: "Heal Block", type1: "Psychic", category: "Status", pp: 15, power: "-", accuracy: 100}
move[378] = {name_en: "Wring Out", type1: "Normal", category: "Special", pp: 5, power: "-", accuracy: 100}
move[379] = {name_en: "Power Trick", type1: "Psychic", category: "Status", pp: 10, power: "-", accuracy: "-"}
move[380] = {name_en: "Gastro Acid", type1: "Poison", category: "Status", pp: 10, power: "-", accuracy: 100}
move[381] = {name_en: "Lucky Chant", type1: "Normal", category: "Status", pp: 30, power: "-", accuracy: "-"}
move[382] = {name_en: "Me First", type1: "Normal", category: "Status", pp: 20, power: "-", accuracy: "-"}
move[383] = {name_en: "Copycat", type1: "Normal", category: "Status", pp: 20, power: "-", accuracy: "-"}
move[384] = {name_en: "Power Swap", type1: "Psychic", category: "Status", pp: 10, power: "-", accuracy: "-"}
move[385] = {name_en: "Guard Swap", type1: "Psychic", category: "Status", pp: 10, power: "-", accuracy: "-"}
move[386] = {name_en: "Punishment", type1: "Dark", category: "Physical", pp: 5, power: "-", accuracy: 100}
move[387] = {name_en: "Last Resort", type1: "Normal", category: "Physical", pp: 5, power: 140, accuracy: 100}
move[388] = {name_en: "Worry Seed", type1: "Grass", category: "Status", pp: 10, power: "-", accuracy: 100}
move[389] = {name_en: "Sucker Punch", type1: "Dark", category: "Physical", pp: 5, power: 80, accuracy: 100}
move[390] = {name_en: "Toxic Spikes", type1: "Poison", category: "Status", pp: 20, power: "-", accuracy: "-"}
move[391] = {name_en: "Heart Swap", type1: "Psychic", category: "Status", pp: 10, power: "-", accuracy: "-"}
move[392] = {name_en: "Aqua Ring", type1: "Water", category: "Status", pp: 20, power: "-", accuracy: "-"}
move[393] = {name_en: "Magnet Rise", type1: "Electric", category: "Status", pp: 10, power: "-", accuracy: "-"}
move[394] = {name_en: "Flare Blitz", type1: "Fire", category: "Physical", pp: 15, power: 120, accuracy: 100}
move[395] = {name_en: "Force Palm", type1: "Fighting", category: "Physical", pp: 10, power: 60, accuracy: 100}
move[396] = {name_en: "Aura Sphere", type1: "Fighting", category: "Special", pp: 20, power: 80, accuracy: "-"}
move[397] = {name_en: "Rock Polish", type1: "Rock", category: "Status", pp: 20, power: "-", accuracy: "-"}
move[398] = {name_en: "Poison Jab", type1: "Poison", category: "Physical", pp: 20, power: 80, accuracy: 100}
move[399] = {name_en: "Dark Pulse", type1: "Dark", category: "Special", pp: 15, power: 80, accuracy: 100}
move[400] = {name_en: "Night Slash", type1: "Dark", category: "Physical", pp: 15, power: 70, accuracy: 100}
move[401] = {name_en: "Aqua Tail", type1: "Water", category: "Physical", pp: 10, power: 90, accuracy: 90}
move[402] = {name_en: "Seed Bomb", type1: "Grass", category: "Physical", pp: 15, power: 80, accuracy: 100}
move[403] = {name_en: "Air Slash", type1: "Flying", category: "Special", pp: 15, power: 75, accuracy: 95}
move[404] = {name_en: "X-Scissor", type1: "Bug", category: "Physical", pp: 15, power: 80, accuracy: 100}
move[405] = {name_en: "Bug Buzz", type1: "Bug", category: "Special", pp: 10, power: 90, accuracy: 100}
move[406] = {name_en: "Dragon Pulse", type1: "Dragon", category: "Special", pp: 10, power: 85, accuracy: 100}
move[407] = {name_en: "Dragon Rush", type1: "Dragon", category: "Physical", pp: 10, power: 100, accuracy: 75}
move[408] = {name_en: "Power Gem", type1: "Rock", category: "Special", pp: 20, power: 80, accuracy: 100}
move[409] = {name_en: "Drain Punch", type1: "Fighting", category: "Physical", pp: 10, power: 75, accuracy: 100}
move[410] = {name_en: "Vacuum Wave", type1: "Fighting", category: "Special", pp: 30, power: 40, accuracy: 100}
move[411] = {name_en: "Focus Blast", type1: "Fighting", category: "Special", pp: 5, power: 120, accuracy: 70}
move[412] = {name_en: "Energy Ball", type1: "Grass", category: "Special", pp: 10, power: 90, accuracy: 100}
move[413] = {name_en: "Brave Bird", type1: "Flying", category: "Physical", pp: 15, power: 120, accuracy: 100}
move[414] = {name_en: "Earth Power", type1: "Ground", category: "Special", pp: 10, power: 90, accuracy: 100}
move[415] = {name_en: "Switcheroo", type1: "Dark", category: "Status", pp: 10, power: "-", accuracy: 100}
move[416] = {name_en: "Giga Impact", type1: "Normal", category: "Physical", pp: 5, power: 150, accuracy: 90}
move[417] = {name_en: "Nasty Plot", type1: "Dark", category: "Status", pp: 20, power: "-", accuracy: "-"}
move[418] = {name_en: "Bullet Punch", type1: "Steel", category: "Physical", pp: 30, power: 40, accuracy: 100}
move[419] = {name_en: "Avalanche", type1: "Ice", category: "Physical", pp: 10, power: 60, accuracy: 100}
move[420] = {name_en: "Ice Shard", type1: "Ice", category: "Physical", pp: 30, power: 40, accuracy: 100}
move[421] = {name_en: "Shadow Claw", type1: "Ghost", category: "Physical", pp: 15, power: 70, accuracy: 100}
move[422] = {name_en: "Thunder Fang", type1: "Electric", category: "Physical", pp: 15, power: 65, accuracy: 95}
move[423] = {name_en: "Ice Fang", type1: "Ice", category: "Physical", pp: 15, power: 65, accuracy: 95}
move[424] = {name_en: "Fire Fang", type1: "Fire", category: "Physical", pp: 15, power: 65, accuracy: 95}
move[425] = {name_en: "Shadow Sneak", type1: "Ghost", category: "Physical", pp: 30, power: 40, accuracy: 100}
move[426] = {name_en: "Mud Bomb", type1: "Ground", category: "Special", pp: 10, power: 65, accuracy: 85}
move[427] = {name_en: "Psycho Cut", type1: "Psychic", category: "Physical", pp: 20, power: 70, accuracy: 100}
move[428] = {name_en: "Zen Headbutt", type1: "Psychic", category: "Physical", pp: 15, power: 80, accuracy: 90}
move[429] = {name_en: "Mirror Shot", type1: "Steel", category: "Special", pp: 10, power: 65, accuracy: 85}
move[430] = {name_en: "Flash Cannon", type1: "Steel", category: "Special", pp: 10, power: 80, accuracy: 100}
move[431] = {name_en: "Rock Climb", type1: "Normal", category: "Physical", pp: 20, power: 90, accuracy: 85}
move[432] = {name_en: "Defog", type1: "Flying", category: "Status", pp: 15, power: "-", accuracy: "-"}
move[433] = {name_en: "Trick Room", type1: "Psychic", category: "Status", pp: 5, power: "-", accuracy: "-"}
move[434] = {name_en: "Draco Meteor", type1: "Dragon", category: "Special", pp: 5, power: 130, accuracy: 90}
move[435] = {name_en: "Discharge", type1: "Electric", category: "Special", pp: 15, power: 80, accuracy: 100}
move[436] = {name_en: "Lava Plume", type1: "Fire", category: "Special", pp: 15, power: 80, accuracy: 100}
move[437] = {name_en: "Leaf Storm", type1: "Grass", category: "Special", pp: 5, power: 130, accuracy: 90}
move[438] = {name_en: "Power Whip", type1: "Grass", category: "Physical", pp: 10, power: 120, accuracy: 85}
move[439] = {name_en: "Rock Wrecker", type1: "Rock", category: "Physical", pp: 5, power: 150, accuracy: 90}
move[440] = {name_en: "Cross Poison", type1: "Poison", category: "Physical", pp: 20, power: 70, accuracy: 100}
move[441] = {name_en: "Gunk Shot", type1: "Poison", category: "Physical", pp: 5, power: 120, accuracy: 80}
move[442] = {name_en: "Iron Head", type1: "Steel", category: "Physical", pp: 15, power: 80, accuracy: 100}
move[443] = {name_en: "Magnet Bomb", type1: "Steel", category: "Physical", pp: 20, power: 60, accuracy: "-"}
move[444] = {name_en: "Stone Edge", type1: "Rock", category: "Physical", pp: 5, power: 100, accuracy: 80}
move[445] = {name_en: "Captivate", type1: "Normal", category: "Status", pp: 20, power: "-", accuracy: 100}
move[446] = {name_en: "Stealth Rock", type1: "Rock", category: "Status", pp: 20, power: "-", accuracy: "-"}
move[447] = {name_en: "Grass Knot", type1: "Grass", category: "Special", pp: 20, power: "-", accuracy: 100}
move[448] = {name_en: "Chatter", type1: "Flying", category: "Special", pp: 20, power: 65, accuracy: 100}
move[449] = {name_en: "Judgment", type1: "Normal", category: "Special", pp: 10, power: 100, accuracy: 100}
move[450] = {name_en: "Bug Bite", type1: "Bug", category: "Physical", pp: 20, power: 60, accuracy: 100}
move[451] = {name_en: "Charge Beam", type1: "Electric", category: "Special", pp: 10, power: 50, accuracy: 90}
move[452] = {name_en: "Wood Hammer", type1: "Grass", category: "Physical", pp: 15, power: 120, accuracy: 100}
move[453] = {name_en: "Aqua Jet", type1: "Water", category: "Physical", pp: 20, power: 40, accuracy: 100}
move[454] = {name_en: "Attack Order", type1: "Bug", category: "Physical", pp: 15, power: 90, accuracy: 100}
move[455] = {name_en: "Defend Order", type1: "Bug", category: "Status", pp: 10, power: "-", accuracy: "-"}
move[456] = {name_en: "Heal Order", type1: "Bug", category: "Status", pp: 10, power: "-", accuracy: "-"}
move[457] = {name_en: "Head Smash", type1: "Rock", category: "Physical", pp: 5, power: 150, accuracy: 80}
move[458] = {name_en: "Double Hit", type1: "Normal", category: "Physical", pp: 10, power: 35, accuracy: 90}
move[459] = {name_en: "Roar of Time", type1: "Dragon", category: "Special", pp: 5, power: 150, accuracy: 90}
move[460] = {name_en: "Spacial Rend", type1: "Dragon", category: "Special", pp: 5, power: 100, accuracy: 95}
move[461] = {name_en: "Lunar Dance", type1: "Psychic", category: "Status", pp: 10, power: "-", accuracy: "-"}
move[462] = {name_en: "Crush Grip", type1: "Normal", category: "Physical", pp: 5, power: "-", accuracy: 100}
move[463] = {name_en: "Magma Storm", type1: "Fire", category: "Special", pp: 5, power: 100, accuracy: 75}
move[464] = {name_en: "Dark Void", type1: "Dark", category: "Status", pp: 10, power: "-", accuracy: 80}
move[465] = {name_en: "Seed Flare", type1: "Grass", category: "Special", pp: 5, power: 120, accuracy: 85}
move[466] = {name_en: "Ominous Wind", type1: "Ghost", category: "Special", pp: 5, power: 60, accuracy: 100}
move[467] = {name_en: "Shadow Force", type1: "Ghost", category: "Physical", pp: 5, power: 120, accuracy: 100}
move[468] = {name_en: "Hone Claws", type1: "Dark", category: "Status", pp: 15, power: "-", accuracy: "-"}
move[469] = {name_en: "Wide Guard", type1: "Rock", category: "Status", pp: 10, power: "-", accuracy: "-"}
move[470] = {name_en: "Guard Split", type1: "Psychic", category: "Status", pp: 10, power: "-", accuracy: "-"}
move[471] = {name_en: "Power Split", type1: "Psychic", category: "Status", pp: 10, power: "-", accuracy: "-"}
move[472] = {name_en: "Wonder Room", type1: "Psychic", category: "Status", pp: 10, power: "-", accuracy: "-"}
move[473] = {name_en: "Psyshock", type1: "Psychic", category: "Special", pp: 10, power: 80, accuracy: 100}
move[474] = {name_en: "Venoshock", type1: "Poison", category: "Special", pp: 10, power: 65, accuracy: 100}
move[475] = {name_en: "Autotomize", type1: "Steel", category: "Status", pp: 15, power: "-", accuracy: "-"}
move[476] = {name_en: "Rage Powder", type1: "Bug", category: "Status", pp: 20, power: "-", accuracy: "-"}
move[477] = {name_en: "Telekinesis", type1: "Psychic", category: "Status", pp: 15, power: "-", accuracy: "-"}
move[478] = {name_en: "Magic Room", type1: "Psychic", category: "Status", pp: 10, power: "-", accuracy: "-"}
move[479] = {name_en: "Smack Down", type1: "Rock", category: "Physical", pp: 15, power: 50, accuracy: 100}
move[480] = {name_en: "Storm Throw", type1: "Fighting", category: "Physical", pp: 10, power: 60, accuracy: 100}
move[481] = {name_en: "Flame Burst", type1: "Fire", category: "Special", pp: 15, power: 70, accuracy: 100}
move[482] = {name_en: "Sludge Wave", type1: "Poison", category: "Special", pp: 10, power: 95, accuracy: 100}
move[483] = {name_en: "Quiver Dance", type1: "Bug", category: "Status", pp: 20, power: "-", accuracy: "-"}
move[484] = {name_en: "Heavy Slam", type1: "Steel", category: "Physical", pp: 10, power: "-", accuracy: 100}
move[485] = {name_en: "Synchronoise", type1: "Psychic", category: "Special", pp: 15, power: 120, accuracy: 100}
move[486] = {name_en: "Electro Ball", type1: "Electric", category: "Special", pp: 10, power: "-", accuracy: 100}
move[487] = {name_en: "Soak", type1: "Water", category: "Status", pp: 20, power: "-", accuracy: 100}
move[488] = {name_en: "Flame Charge", type1: "Fire", category: "Physical", pp: 20, power: 50, accuracy: 100}
move[489] = {name_en: "Coil", type1: "Poison", category: "Status", pp: 20, power: "-", accuracy: "-"}
move[490] = {name_en: "Low Sweep", type1: "Fighting", category: "Physical", pp: 20, power: 65, accuracy: 100}
move[491] = {name_en: "Acid Spray", type1: "Poison", category: "Special", pp: 20, power: 40, accuracy: 100}
move[492] = {name_en: "Foul Play", type1: "Dark", category: "Physical", pp: 15, power: 95, accuracy: 100}
move[493] = {name_en: "Simple Beam", type1: "Normal", category: "Status", pp: 15, power: "-", accuracy: 100}
move[494] = {name_en: "Entrainment", type1: "Normal", category: "Status", pp: 15, power: "-", accuracy: 100}
move[495] = {name_en: "After You", type1: "Normal", category: "Status", pp: 15, power: "-", accuracy: "-"}
move[496] = {name_en: "Round", type1: "Normal", category: "Special", pp: 15, power: 60, accuracy: 100}
move[497] = {name_en: "Echoed Voice", type1: "Normal", category: "Special", pp: 15, power: 40, accuracy: 100}
move[498] = {name_en: "Chip Away", type1: "Normal", category: "Physical", pp: 20, power: 70, accuracy: 100}
move[499] = {name_en: "Clear Smog", type1: "Poison", category: "Special", pp: 15, power: 50, accuracy: "-"}
move[500] = {name_en: "Stored Power", type1: "Psychic", category: "Special", pp: 10, power: 20, accuracy: 100}
move[501] = {name_en: "Quick Guard", type1: "Fighting", category: "Status", pp: 15, power: "-", accuracy: "-"}
move[502] = {name_en: "Ally Switch", type1: "Psychic", category: "Status", pp: 15, power: "-", accuracy: "-"}
move[503] = {name_en: "Scald", type1: "Water", category: "Special", pp: 15, power: 80, accuracy: 100}
move[504] = {name_en: "Shell Smash", type1: "Normal", category: "Status", pp: 15, power: "-", accuracy: "-"}
move[505] = {name_en: "Heal Pulse", type1: "Psychic", category: "Status", pp: 10, power: "-", accuracy: "-"}
move[506] = {name_en: "Hex", type1: "Ghost", category: "Special", pp: 10, power: 65, accuracy: 100}
move[507] = {name_en: "Sky Drop", type1: "Flying", category: "Physical", pp: 10, power: 60, accuracy: 100}
move[508] = {name_en: "Shift Gear", type1: "Steel", category: "Status", pp: 10, power: "-", accuracy: "-"}
move[509] = {name_en: "Circle Throw", type1: "Fighting", category: "Physical", pp: 10, power: 60, accuracy: 90}
move[510] = {name_en: "Incinerate", type1: "Fire", category: "Special", pp: 15, power: 60, accuracy: 100}
move[511] = {name_en: "Quash", type1: "Dark", category: "Status", pp: 15, power: "-", accuracy: 100}
move[512] = {name_en: "Acrobatics", type1: "Flying", category: "Physical", pp: 15, power: 55, accuracy: 100}
move[513] = {name_en: "Reflect Type", type1: "Normal", category: "Status", pp: 15, power: "-", accuracy: "-"}
move[514] = {name_en: "Retaliate", type1: "Normal", category: "Physical", pp: 5, power: 70, accuracy: 100}
move[515] = {name_en: "Final Gambit", type1: "Fighting", category: "Special", pp: 5, power: "-", accuracy: 100}
move[516] = {name_en: "Bestow", type1: "Normal", category: "Status", pp: 15, power: "-", accuracy: "-"}
move[517] = {name_en: "Inferno", type1: "Fire", category: "Special", pp: 5, power: 100, accuracy: 50}
move[518] = {name_en: "Water Pledge", type1: "Water", category: "Special", pp: 10, power: 80, accuracy: 100}
move[519] = {name_en: "Fire Pledge", type1: "Fire", category: "Special", pp: 10, power: 80, accuracy: 100}
move[520] = {name_en: "Grass Pledge", type1: "Grass", category: "Special", pp: 10, power: 80, accuracy: 100}
move[521] = {name_en: "Volt Switch", type1: "Electric", category: "Special", pp: 20, power: 70, accuracy: 100}
move[522] = {name_en: "Struggle Bug", type1: "Bug", category: "Special", pp: 20, power: 50, accuracy: 100}
move[523] = {name_en: "Bulldoze", type1: "Ground", category: "Physical", pp: 20, power: 60, accuracy: 100}
move[524] = {name_en: "Frost Breath", type1: "Ice", category: "Special", pp: 10, power: 60, accuracy: 90}
move[525] = {name_en: "Dragon Tail", type1: "Dragon", category: "Physical", pp: 10, power: 60, accuracy: 90}
move[526] = {name_en: "Work Up", type1: "Normal", category: "Status", pp: 30, power: "-", accuracy: "-"}
move[527] = {name_en: "Electroweb", type1: "Electric", category: "Special", pp: 15, power: 55, accuracy: 95}
move[528] = {name_en: "Wild Charge", type1: "Electric", category: "Physical", pp: 15, power: 90, accuracy: 100}
move[529] = {name_en: "Drill Run", type1: "Ground", category: "Physical", pp: 10, power: 80, accuracy: 95}
move[530] = {name_en: "Dual Chop", type1: "Dragon", category: "Physical", pp: 15, power: 40, accuracy: 90}
move[531] = {name_en: "Heart Stamp", type1: "Psychic", category: "Physical", pp: 25, power: 60, accuracy: 100}
move[532] = {name_en: "Horn Leech", type1: "Grass", category: "Physical", pp: 10, power: 75, accuracy: 100}
move[533] = {name_en: "Sacred Sword", type1: "Fighting", category: "Physical", pp: 15, power: 90, accuracy: 100}
move[534] = {name_en: "Razor Shell", type1: "Water", category: "Physical", pp: 10, power: 75, accuracy: 95}
move[535] = {name_en: "Heat Crash", type1: "Fire", category: "Physical", pp: 10, power: "-", accuracy: 100}
move[536] = {name_en: "Leaf Tornado", type1: "Grass", category: "Special", pp: 10, power: 65, accuracy: 90}
move[537] = {name_en: "Steamroller", type1: "Bug", category: "Physical", pp: 20, power: 65, accuracy: 100}
move[538] = {name_en: "Cotton Guard", type1: "Grass", category: "Status", pp: 10, power: "-", accuracy: "-"}
move[539] = {name_en: "Night Daze", type1: "Dark", category: "Special", pp: 10, power: 85, accuracy: 95}
move[540] = {name_en: "Psystrike", type1: "Psychic", category: "Special", pp: 10, power: 100, accuracy: 100}
move[541] = {name_en: "Tail Slap", type1: "Normal", category: "Physical", pp: 10, power: 25, accuracy: 85}
move[542] = {name_en: "Hurricane", type1: "Flying", category: "Special", pp: 10, power: 110, accuracy: 70}
move[543] = {name_en: "Head Charge", type1: "Normal", category: "Physical", pp: 15, power: 120, accuracy: 100}
move[544] = {name_en: "Gear Grind", type1: "Steel", category: "Physical", pp: 15, power: 50, accuracy: 85}
move[545] = {name_en: "Searing Shot", type1: "Fire", category: "Special", pp: 5, power: 100, accuracy: 100}
move[546] = {name_en: "Techno Blast", type1: "Normal", category: "Special", pp: 5, power: 120, accuracy: 100}
move[547] = {name_en: "Relic Song", type1: "Normal", category: "Special", pp: 10, power: 75, accuracy: 100}
move[548] = {name_en: "Secret Sword", type1: "Fighting", category: "Special", pp: 10, power: 85, accuracy: 100}
move[549] = {name_en: "Glaciate", type1: "Ice", category: "Special", pp: 10, power: 65, accuracy: 95}
move[550] = {name_en: "Bolt Strike", type1: "Electric", category: "Physical", pp: 5, power: 130, accuracy: 85}
move[551] = {name_en: "Blue Flare", type1: "Fire", category: "Special", pp: 5, power: 130, accuracy: 85}
move[552] = {name_en: "Fiery Dance", type1: "Fire", category: "Special", pp: 10, power: 80, accuracy: 100}
move[553] = {name_en: "Freeze Shock", type1: "Ice", category: "Physical", pp: 5, power: 140, accuracy: 90}
move[554] = {name_en: "Ice Burn", type1: "Ice", category: "Special", pp: 5, power: 140, accuracy: 90}
move[555] = {name_en: "Snarl", type1: "Dark", category: "Special", pp: 15, power: 55, accuracy: 95}
move[556] = {name_en: "Icicle Crash", type1: "Ice", category: "Physical", pp: 10, power: 85, accuracy: 90}
move[557] = {name_en: "V-create", type1: "Fire", category: "Physical", pp: 5, power: 180, accuracy: 95}
move[558] = {name_en: "Fusion Flare", type1: "Fire", category: "Special", pp: 5, power: 100, accuracy: 100}
move[559] = {name_en: "Fusion Bolt", type1: "Electric", category: "Physical", pp: 5, power: 100, accuracy: 100}
move[560] = {name_en: "Flying Press", type1: "Fighting", category: "Physical", pp: 10, power: 80, accuracy: 95}
move[561] = {name_en: "Mat Block", type1: "Fighting", category: "Status", pp: 10, power: "-", accuracy: "-"}
move[562] = {name_en: "Belch", type1: "Poison", category: "Special", pp: 10, power: 120, accuracy: 90}
move[563] = {name_en: "Rototiller", type1: "Ground", category: "Status", pp: 10, power: "-", accuracy: "-"}
move[564] = {name_en: "Sticky Web", type1: "Bug", category: "Status", pp: 20, power: "-", accuracy: "-"}
move[565] = {name_en: "Fell Stinger", type1: "Bug", category: "Physical", pp: 25, power: 30, accuracy: 100}
move[566] = {name_en: "Phantom Force", type1: "Ghost", category: "Physical", pp: 10, power: 90, accuracy: 100}
move[567] = {name_en: "Trick-or-Treat", type1: "Ghost", category: "Status", pp: 20, power: "-", accuracy: 100}
move[568] = {name_en: "Noble Roar", type1: "Normal", category: "Status", pp: 30, power: "-", accuracy: 100}
move[569] = {name_en: "Ion Deluge", type1: "Electric", category: "Status", pp: 25, power: "-", accuracy: "-"}
move[570] = {name_en: "Parabolic Charge", type1: "Electric", category: "Special", pp: 20, power: 50, accuracy: 100}
move[571] = {name_en: "Forest's Curse", type1: "Grass", category: "Status", pp: 20, power: "-", accuracy: 100}
move[572] = {name_en: "Petal Blizzard", type1: "Grass", category: "Physical", pp: 15, power: 90, accuracy: 100}
move[573] = {name_en: "Freeze-Dry", type1: "Ice", category: "Special", pp: 20, power: 70, accuracy: 100}
move[574] = {name_en: "Disarming Voice", type1: "Fairy", category: "Special", pp: 15, power: 40, accuracy: "-"}
move[575] = {name_en: "Parting Shot", type1: "Dark", category: "Status", pp: 20, power: "-", accuracy: 100}
move[576] = {name_en: "Topsy-Turvy", type1: "Dark", category: "Status", pp: 20, power: "-", accuracy: 100}
move[577] = {name_en: "Draining Kiss", type1: "Fairy", category: "Special", pp: 10, power: 50, accuracy: 100}
move[578] = {name_en: "Crafty Shield", type1: "Fairy", category: "Status", pp: 10, power: "-", accuracy: "-"}
move[579] = {name_en: "Flower Shield", type1: "Fairy", category: "Status", pp: 10, power: "-", accuracy: "-"}
move[580] = {name_en: "Grassy Terrain", type1: "Grass", category: "Status", pp: 10, power: "-", accuracy: "-"}
move[581] = {name_en: "Misty Terrain", type1: "Fairy", category: "Status", pp: 10, power: "-", accuracy: "-"}
move[582] = {name_en: "Electrify", type1: "Electric", category: "Status", pp: 20, power: "-", accuracy: "-"}
move[583] = {name_en: "Play Rough", type1: "Fairy", category: "Physical", pp: 10, power: 90, accuracy: 90}
move[584] = {name_en: "Fairy Wind", type1: "Fairy", category: "Special", pp: 30, power: 40, accuracy: "-"}
move[585] = {name_en: "Moonblast", type1: "Fairy", category: "Special", pp: 15, power: 95, accuracy: 100}
move[586] = {name_en: "Boomburst", type1: "Normal", category: "Special", pp: 10, power: 140, accuracy: 100}
move[587] = {name_en: "Fairy Lock", type1: "Fairy", category: "Status", pp: 10, power: "-", accuracy: "-"}
move[588] = {name_en: "King's Shield", type1: "Steel", category: "Status", pp: 10, power: "-", accuracy: "-"}
move[589] = {name_en: "Play Nice", type1: "Normal", category: "Status", pp: 20, power: "-", accuracy: "-"}
move[590] = {name_en: "Confide", type1: "Normal", category: "Status", pp: 20, power: "-", accuracy: "-"}
move[591] = {name_en: "Diamond Storm", type1: "Rock", category: "Physical", pp: 5, power: 100, accuracy: 95}
move[592] = {name_en: "Steam Eruption", type1: "Water", category: "Special", pp: 5, power: 110, accuracy: 95}
move[593] = {name_en: "Hyperspace Hole", type1: "Psychic", category: "Special", pp: 5, power: 80, accuracy: "-"}
move[594] = {name_en: "Water Shuriken", type1: "Water", category: "Physical", pp: 20, power: 15, accuracy: 100}
move[595] = {name_en: "Mystical Fire", type1: "Fire", category: "Special", pp: 10, power: 65, accuracy: 100}
move[596] = {name_en: "Spiky Shield", type1: "Grass", category: "Status", pp: 10, power: "-", accuracy: "-"}
move[597] = {name_en: "Aromatic Mist", type1: "Fairy", category: "Status", pp: 20, power: "-", accuracy: "-"}
move[598] = {name_en: "Eerie Impulse", type1: "Electric", category: "Status", pp: 15, power: "-", accuracy: 100}
move[599] = {name_en: "Venom Drench", type1: "Poison", category: "Status", pp: 20, power: "-", accuracy: 100}
move[600] = {name_en: "Powder", type1: "Bug", category: "Status", pp: 20, power: "-", accuracy: 100}
move[601] = {name_en: "Geomancy", type1: "Fairy", category: "Status", pp: 10, power: "-", accuracy: "-"}
move[602] = {name_en: "Magnetic Flux", type1: "Electric", category: "Status", pp: 20, power: "-", accuracy: "-"}
move[603] = {name_en: "Happy Hour", type1: "Normal", category: "Status", pp: 30, power: "-", accuracy: "-"}
move[604] = {name_en: "Electric Terrain", type1: "Electric", category: "Status", pp: 10, power: "-", accuracy: "-"}
move[605] = {name_en: "Dazzling Gleam", type1: "Fairy", category: "Special", pp: 10, power: 80, accuracy: 100}
move[606] = {name_en: "Celebrate", type1: "Normal", category: "Status", pp: 40, power: "-", accuracy: "-"}
move[607] = {name_en: "Hold Hands", type1: "Normal", category: "Status", pp: 40, power: "-", accuracy: "-"}
move[608] = {name_en: "Baby-Doll Eyes", type1: "Fairy", category: "Status", pp: 30, power: "-", accuracy: 100}
move[609] = {name_en: "Nuzzle", type1: "Electric", category: "Physical", pp: 20, power: 20, accuracy: 100}
move[610] = {name_en: "Hold Back", type1: "Normal", category: "Physical", pp: 40, power: 40, accuracy: 100}
move[611] = {name_en: "Infestation", type1: "Bug", category: "Special", pp: 20, power: 20, accuracy: 100}
move[612] = {name_en: "Power-Up Punch", type1: "Fighting", category: "Physical", pp: 20, power: 40, accuracy: 100}
move[613] = {name_en: "Oblivion Wing", type1: "Flying", category: "Special", pp: 10, power: 80, accuracy: 100}
move[614] = {name_en: "Thousand Arrows", type1: "Ground", category: "Physical", pp: 10, power: 90, accuracy: 100}
move[615] = {name_en: "Thousand Waves", type1: "Ground", category: "Physical", pp: 10, power: 90, accuracy: 100}
move[616] = {name_en: "Land's Wrath", type1: "Ground", category: "Physical", pp: 10, power: 90, accuracy: 100}
move[617] = {name_en: "Light of Ruin", type1: "Fairy", category: "Special", pp: 5, power: 140, accuracy: 90}
move[618] = {name_en: "Origin Pulse", type1: "Water", category: "Special", pp: 10, power: 110, accuracy: 85}
move[619] = {name_en: "Precipice Blades", type1: "Ground", category: "Physical", pp: 10, power: 120, accuracy: 85}
move[620] = {name_en: "Dragon Ascent", type1: "Flying", category: "Physical", pp: 5, power: 120, accuracy: 100}
move[621] = {name_en: "Hyperspace Fury", type1: "Dark", category: "Physical", pp: 5, power: 100, accuracy: "-"}

module.exports = move;