var typejs = require('./type.js');
var type = typejs.type;

var move = {};

move[1] = {id: 1, name_en: "Pound", type: type["Normal"], category: "Physical", pp: 35, power: 40, accuracy: 100}
move[2] = {id: 2, name_en: "Karate Chop", type: type["Fighting"], category: "Physical", pp: 25, power: 50, accuracy: 100}
move[3] = {id: 3, name_en: "Double Slap", type: type["Normal"], category: "Physical", pp: 10, power: 15, accuracy: 85}
move[4] = {id: 4, name_en: "Comet Punch", type: type["Normal"], category: "Physical", pp: 15, power: 18, accuracy: 85}
move[5] = {id: 5, name_en: "Mega Punch", type: type["Normal"], category: "Physical", pp: 20, power: 80, accuracy: 85}
move[6] = {id: 6, name_en: "Pay Day", type: type["Normal"], category: "Physical", pp: 20, power: 40, accuracy: 100}
move[7] = {id: 7, name_en: "Fire Punch", type: type["Fire"], category: "Physical", pp: 15, power: 75, accuracy: 100}
move[8] = {id: 8, name_en: "Ice Punch", type: type["Ice"], category: "Physical", pp: 15, power: 75, accuracy: 100}
move[9] = {id: 9, name_en: "Thunder Punch", type: type["Electric"], category: "Physical", pp: 15, power: 75, accuracy: 100}
move[10] = {id: 10, name_en: "Scratch", type: type["Normal"], category: "Physical", pp: 35, power: 40, accuracy: 100}
move[11] = {id: 11, name_en: "Vice Grip", type: type["Normal"], category: "Physical", pp: 30, power: 55, accuracy: 100}
move[12] = {id: 12, name_en: "Guillotine", type: type["Normal"], category: "Physical", pp: 5, power: "-", accuracy: "-"}
move[13] = {id: 13, name_en: "Razor Wind", type: type["Normal"], category: "Special", pp: 10, power: 80, accuracy: 100}
move[14] = {id: 14, name_en: "Swords Dance", type: type["Normal"], category: "Status", pp: 20, power: "-", accuracy: "-"}
move[15] = {id: 15, name_en: "Cut", type: type["Normal"], category: "Physical", pp: 30, power: 50, accuracy: 95}
move[16] = {id: 16, name_en: "Gust", type: type["Flying"], category: "Special", pp: 35, power: 40, accuracy: 100}
move[17] = {id: 17, name_en: "Wing Attack", type: type["Flying"], category: "Physical", pp: 35, power: 60, accuracy: 100}
move[18] = {id: 18, name_en: "Whirlwind", type: type["Normal"], category: "Status", pp: 20, power: "-", accuracy: "-"}
move[19] = {id: 19, name_en: "Fly", type: type["Flying"], category: "Physical", pp: 15, power: 90, accuracy: 95}
move[20] = {id: 20, name_en: "Bind", type: type["Normal"], category: "Physical", pp: 20, power: 15, accuracy: 85}
move[21] = {id: 21, name_en: "Slam", type: type["Normal"], category: "Physical", pp: 20, power: 80, accuracy: 75}
move[22] = {id: 22, name_en: "Vine Whip", type: type["Grass"], category: "Physical", pp: 25, power: 45, accuracy: 100}
move[23] = {id: 23, name_en: "Stomp", type: type["Normal"], category: "Physical", pp: 20, power: 65, accuracy: 100}
move[24] = {id: 24, name_en: "Double Kick", type: type["Fighting"], category: "Physical", pp: 30, power: 30, accuracy: 100}
move[25] = {id: 25, name_en: "Mega Kick", type: type["Normal"], category: "Physical", pp: 5, power: 120, accuracy: 75}
move[26] = {id: 26, name_en: "Jump Kick", type: type["Fighting"], category: "Physical", pp: 10, power: 100, accuracy: 95}
move[27] = {id: 27, name_en: "Rolling Kick", type: type["Fighting"], category: "Physical", pp: 15, power: 60, accuracy: 85}
move[28] = {id: 28, name_en: "Sand Attack", type: type["Ground"], category: "Status", pp: 15, power: "-", accuracy: 100}
move[29] = {id: 29, name_en: "Headbutt", type: type["Normal"], category: "Physical", pp: 15, power: 70, accuracy: 100}
move[30] = {id: 30, name_en: "Horn Attack", type: type["Normal"], category: "Physical", pp: 25, power: 65, accuracy: 100}
move[31] = {id: 31, name_en: "Fury Attack", type: type["Normal"], category: "Physical", pp: 20, power: 15, accuracy: 85}
move[32] = {id: 32, name_en: "Horn Drill", type: type["Normal"], category: "Physical", pp: 5, power: "-", accuracy: "-"}
move[33] = {id: 33, name_en: "Tackle", type: type["Normal"], category: "Physical", pp: 35, power: 50, accuracy: 100}
move[34] = {id: 34, name_en: "Body Slam", type: type["Normal"], category: "Physical", pp: 15, power: 85, accuracy: 100}
move[35] = {id: 35, name_en: "Wrap", type: type["Normal"], category: "Physical", pp: 20, power: 15, accuracy: 90}
move[36] = {id: 36, name_en: "Take Down", type: type["Normal"], category: "Physical", pp: 20, power: 90, accuracy: 85}
move[37] = {id: 37, name_en: "Thrash", type: type["Normal"], category: "Physical", pp: 10, power: 120, accuracy: 100}
move[38] = {id: 38, name_en: "Double-Edge", type: type["Normal"], category: "Physical", pp: 15, power: 120, accuracy: 100}
move[39] = {id: 39, name_en: "Tail Whip", type: type["Normal"], category: "Status", pp: 30, power: "-", accuracy: 100}
move[40] = {id: 40, name_en: "Poison Sting", type: type["Poison"], category: "Physical", pp: 35, power: 15, accuracy: 100}
move[41] = {id: 41, name_en: "Twineedle", type: type["Bug"], category: "Physical", pp: 20, power: 25, accuracy: 100}
move[42] = {id: 42, name_en: "Pin Missile", type: type["Bug"], category: "Physical", pp: 20, power: 25, accuracy: 95}
move[43] = {id: 43, name_en: "Leer", type: type["Normal"], category: "Status", pp: 30, power: "-", accuracy: 100}
move[44] = {id: 44, name_en: "Bite", type: type["Dark"], category: "Physical", pp: 25, power: 60, accuracy: 100}
move[45] = {id: 45, name_en: "Growl", type: type["Normal"], category: "Status", pp: 40, power: "-", accuracy: 100}
move[46] = {id: 46, name_en: "Roar", type: type["Normal"], category: "Status", pp: 20, power: "-", accuracy: "-"}
move[47] = {id: 47, name_en: "Sing", type: type["Normal"], category: "Status", pp: 15, power: "-", accuracy: 55}
move[48] = {id: 48, name_en: "Supersonic", type: type["Normal"], category: "Status", pp: 20, power: "-", accuracy: 55}
move[49] = {id: 49, name_en: "Sonic Boom", type: type["Normal"], category: "Special", pp: 20, power: "-", accuracy: 90}
move[50] = {id: 50, name_en: "Disable", type: type["Normal"], category: "Status", pp: 20, power: "-", accuracy: 100}
move[51] = {id: 51, name_en: "Acid", type: type["Poison"], category: "Special", pp: 30, power: 40, accuracy: 100}
move[52] = {id: 52, name_en: "Ember", type: type["Fire"], category: "Special", pp: 25, power: 40, accuracy: 100}
move[53] = {id: 53, name_en: "Flamethrower", type: type["Fire"], category: "Special", pp: 15, power: 90, accuracy: 100}
move[54] = {id: 54, name_en: "Mist", type: type["Ice"], category: "Status", pp: 30, power: "-", accuracy: "-"}
move[55] = {id: 55, name_en: "Water Gun", type: type["Water"], category: "Special", pp: 25, power: 40, accuracy: 100}
move[56] = {id: 56, name_en: "Hydro Pump", type: type["Water"], category: "Special", pp: 5, power: 110, accuracy: 80}
move[57] = {id: 57, name_en: "Surf", type: type["Water"], category: "Special", pp: 15, power: 90, accuracy: 100}
move[58] = {id: 58, name_en: "Ice Beam", type: type["Ice"], category: "Special", pp: 10, power: 90, accuracy: 100}
move[59] = {id: 59, name_en: "Blizzard", type: type["Ice"], category: "Special", pp: 5, power: 110, accuracy: 70}
move[60] = {id: 60, name_en: "Psybeam", type: type["Psychic"], category: "Special", pp: 20, power: 65, accuracy: 100}
move[61] = {id: 61, name_en: "Bubble Beam", type: type["Water"], category: "Special", pp: 20, power: 65, accuracy: 100}
move[62] = {id: 62, name_en: "Aurora Beam", type: type["Ice"], category: "Special", pp: 20, power: 65, accuracy: 100}
move[63] = {id: 63, name_en: "Hyper Beam", type: type["Normal"], category: "Special", pp: 5, power: 150, accuracy: 90}
move[64] = {id: 64, name_en: "Peck", type: type["Flying"], category: "Physical", pp: 35, power: 35, accuracy: 100}
move[65] = {id: 65, name_en: "Drill Peck", type: type["Flying"], category: "Physical", pp: 20, power: 80, accuracy: 100}
move[66] = {id: 66, name_en: "Submission", type: type["Fighting"], category: "Physical", pp: 25, power: 80, accuracy: 80}
move[67] = {id: 67, name_en: "Low Kick", type: type["Fighting"], category: "Physical", pp: 20, power: "-", accuracy: 100}
move[68] = {id: 68, name_en: "Counter", type: type["Fighting"], category: "Physical", pp: 20, power: "-", accuracy: 100}
move[69] = {id: 69, name_en: "Seismic Toss", type: type["Fighting"], category: "Physical", pp: 20, power: "-", accuracy: 100}
move[70] = {id: 70, name_en: "Strength", type: type["Normal"], category: "Physical", pp: 15, power: 80, accuracy: 100}
move[71] = {id: 71, name_en: "Absorb", type: type["Grass"], category: "Special", pp: 25, power: 20, accuracy: 100}
move[72] = {id: 72, name_en: "Mega Drain", type: type["Grass"], category: "Special", pp: 15, power: 40, accuracy: 100}
move[73] = {id: 73, name_en: "Leech Seed", type: type["Grass"], category: "Status", pp: 10, power: "-", accuracy: 90}
move[74] = {id: 74, name_en: "Growth", type: type["Normal"], category: "Status", pp: 20, power: "-", accuracy: "-"}
move[75] = {id: 75, name_en: "Razor Leaf", type: type["Grass"], category: "Physical", pp: 25, power: 55, accuracy: 95}
move[76] = {id: 76, name_en: "Solar Beam", type: type["Grass"], category: "Special", pp: 10, power: 120, accuracy: 100}
move[77] = {id: 77, name_en: "Poison Powder", type: type["Poison"], category: "Status", pp: 35, power: "-", accuracy: 75}
move[78] = {id: 78, name_en: "Stun Spore", type: type["Grass"], category: "Status", pp: 30, power: "-", accuracy: 75}
move[79] = {id: 79, name_en: "Sleep Powder", type: type["Grass"], category: "Status", pp: 15, power: "-", accuracy: 75}
move[80] = {id: 80, name_en: "Petal Dance", type: type["Grass"], category: "Special", pp: 10, power: 120, accuracy: 100}
move[81] = {id: 81, name_en: "String Shot", type: type["Bug"], category: "Status", pp: 40, power: "-", accuracy: 95}
move[82] = {id: 82, name_en: "Dragon Rage", type: type["Dragon"], category: "Special", pp: 10, power: "-", accuracy: 100}
move[83] = {id: 83, name_en: "Fire Spin", type: type["Fire"], category: "Special", pp: 15, power: 35, accuracy: 85}
move[84] = {id: 84, name_en: "Thunder Shock", type: type["Electric"], category: "Special", pp: 30, power: 40, accuracy: 100}
move[85] = {id: 85, name_en: "Thunderbolt", type: type["Electric"], category: "Special", pp: 15, power: 90, accuracy: 100}
move[86] = {id: 86, name_en: "Thunder Wave", type: type["Electric"], category: "Status", pp: 20, power: "-", accuracy: 100}
move[87] = {id: 87, name_en: "Thunder", type: type["Electric"], category: "Special", pp: 10, power: 110, accuracy: 70}
move[88] = {id: 88, name_en: "Rock Throw", type: type["Rock"], category: "Physical", pp: 15, power: 50, accuracy: 90}
move[89] = {id: 89, name_en: "Earthquake", type: type["Ground"], category: "Physical", pp: 10, power: 100, accuracy: 100}
move[90] = {id: 90, name_en: "Fissure", type: type["Ground"], category: "Physical", pp: 5, power: "-", accuracy: "-"}
move[91] = {id: 91, name_en: "Dig", type: type["Ground"], category: "Physical", pp: 10, power: 80, accuracy: 100}
move[92] = {id: 92, name_en: "Toxic", type: type["Poison"], category: "Status", pp: 10, power: "-", accuracy: 90}
move[93] = {id: 93, name_en: "Confusion", type: type["Psychic"], category: "Special", pp: 25, power: 50, accuracy: 100}
move[94] = {id: 94, name_en: "Psychic", type: type["Psychic"], category: "Special", pp: 10, power: 90, accuracy: 100}
move[95] = {id: 95, name_en: "Hypnosis", type: type["Psychic"], category: "Status", pp: 20, power: "-", accuracy: 60}
move[96] = {id: 96, name_en: "Meditate", type: type["Psychic"], category: "Status", pp: 40, power: "-", accuracy: "-"}
move[97] = {id: 97, name_en: "Agility", type: type["Psychic"], category: "Status", pp: 30, power: "-", accuracy: "-"}
move[98] = {id: 98, name_en: "Quick Attack", type: type["Normal"], category: "Physical", pp: 30, power: 40, accuracy: 100}
move[99] = {id: 99, name_en: "Rage", type: type["Normal"], category: "Physical", pp: 20, power: 20, accuracy: 100}
move[100] = {id: 100, name_en: "Teleport", type: type["Psychic"], category: "Status", pp: 20, power: "-", accuracy: "-"}
move[101] = {id: 101, name_en: "Night Shade", type: type["Ghost"], category: "Special", pp: 15, power: "-", accuracy: 100}
move[102] = {id: 102, name_en: "Mimic", type: type["Normal"], category: "Status", pp: 10, power: "-", accuracy: 100}
move[103] = {id: 103, name_en: "Screech", type: type["Normal"], category: "Status", pp: 40, power: "-", accuracy: 85}
move[104] = {id: 104, name_en: "Double Team", type: type["Normal"], category: "Status", pp: 15, power: "-", accuracy: "-"}
move[105] = {id: 105, name_en: "Recover", type: type["Normal"], category: "Status", pp: 10, power: "-", accuracy: "-"}
move[106] = {id: 106, name_en: "Harden", type: type["Normal"], category: "Status", pp: 30, power: "-", accuracy: "-"}
move[107] = {id: 107, name_en: "Minimize", type: type["Normal"], category: "Status", pp: 10, power: "-", accuracy: "-"}
move[108] = {id: 108, name_en: "Smokescreen", type: type["Normal"], category: "Status", pp: 20, power: "-", accuracy: 100}
move[109] = {id: 109, name_en: "Confuse Ray", type: type["Ghost"], category: "Status", pp: 10, power: "-", accuracy: 100}
move[110] = {id: 110, name_en: "Withdraw", type: type["Water"], category: "Status", pp: 40, power: "-", accuracy: "-"}
move[111] = {id: 111, name_en: "Defense Curl", type: type["Normal"], category: "Status", pp: 40, power: "-", accuracy: "-"}
move[112] = {id: 112, name_en: "Barrier", type: type["Psychic"], category: "Status", pp: 20, power: "-", accuracy: "-"}
move[113] = {id: 113, name_en: "Light Screen", type: type["Psychic"], category: "Status", pp: 30, power: "-", accuracy: "-"}
move[114] = {id: 114, name_en: "Haze", type: type["Ice"], category: "Status", pp: 30, power: "-", accuracy: "-"}
move[115] = {id: 115, name_en: "Reflect", type: type["Psychic"], category: "Status", pp: 20, power: "-", accuracy: "-"}
move[116] = {id: 116, name_en: "Focus Energy", type: type["Normal"], category: "Status", pp: 30, power: "-", accuracy: "-"}
move[117] = {id: 117, name_en: "Bide", type: type["Normal"], category: "Physical", pp: 10, power: "-", accuracy: 100}
move[118] = {id: 118, name_en: "Metronome", type: type["Normal"], category: "Status", pp: 10, power: "-", accuracy: "-"}
move[119] = {id: 119, name_en: "Mirror Move", type: type["Flying"], category: "Status", pp: 20, power: "-", accuracy: "-"}
move[120] = {id: 120, name_en: "Self-Destruct", type: type["Normal"], category: "Physical", pp: 5, power: 200, accuracy: 100}
move[121] = {id: 121, name_en: "Egg Bomb", type: type["Normal"], category: "Physical", pp: 10, power: 100, accuracy: 75}
move[122] = {id: 122, name_en: "Lick", type: type["Ghost"], category: "Physical", pp: 30, power: 30, accuracy: 100}
move[123] = {id: 123, name_en: "Smog", type: type["Poison"], category: "Special", pp: 20, power: 30, accuracy: 70}
move[124] = {id: 124, name_en: "Sludge", type: type["Poison"], category: "Special", pp: 20, power: 65, accuracy: 100}
move[125] = {id: 125, name_en: "Bone Club", type: type["Ground"], category: "Physical", pp: 20, power: 65, accuracy: 85}
move[126] = {id: 126, name_en: "Fire Blast", type: type["Fire"], category: "Special", pp: 5, power: 110, accuracy: 85}
move[127] = {id: 127, name_en: "Waterfall", type: type["Water"], category: "Physical", pp: 15, power: 80, accuracy: 100}
move[128] = {id: 128, name_en: "Clamp", type: type["Water"], category: "Physical", pp: 15, power: 35, accuracy: 85}
move[129] = {id: 129, name_en: "Swift", type: type["Normal"], category: "Special", pp: 20, power: 60, accuracy: "-"}
move[130] = {id: 130, name_en: "Skull Bash", type: type["Normal"], category: "Physical", pp: 10, power: 130, accuracy: 100}
move[131] = {id: 131, name_en: "Spike Cannon", type: type["Normal"], category: "Physical", pp: 15, power: 20, accuracy: 100}
move[132] = {id: 132, name_en: "Constrict", type: type["Normal"], category: "Physical", pp: 35, power: 10, accuracy: 100}
move[133] = {id: 133, name_en: "Amnesia", type: type["Psychic"], category: "Status", pp: 20, power: "-", accuracy: "-"}
move[134] = {id: 134, name_en: "Kinesis", type: type["Psychic"], category: "Status", pp: 15, power: "-", accuracy: 80}
move[135] = {id: 135, name_en: "Soft-Boiled", type: type["Normal"], category: "Status", pp: 10, power: "-", accuracy: "-"}
move[136] = {id: 136, name_en: "High Jump Kick", type: type["Fighting"], category: "Physical", pp: 10, power: 130, accuracy: 90}
move[137] = {id: 137, name_en: "Glare", type: type["Normal"], category: "Status", pp: 30, power: "-", accuracy: 100}
move[138] = {id: 138, name_en: "Dream Eater", type: type["Psychic"], category: "Special", pp: 15, power: 100, accuracy: 100}
move[139] = {id: 139, name_en: "Poison Gas", type: type["Poison"], category: "Status", pp: 40, power: "-", accuracy: 90}
move[140] = {id: 140, name_en: "Barrage", type: type["Normal"], category: "Physical", pp: 20, power: 15, accuracy: 85}
move[141] = {id: 141, name_en: "Leech Life", type: type["Bug"], category: "Physical", pp: 15, power: 20, accuracy: 100}
move[142] = {id: 142, name_en: "Lovely Kiss", type: type["Normal"], category: "Status", pp: 10, power: "-", accuracy: 75}
move[143] = {id: 143, name_en: "Sky Attack", type: type["Flying"], category: "Physical", pp: 5, power: 140, accuracy: 90}
move[144] = {id: 144, name_en: "Transform", type: type["Normal"], category: "Status", pp: 10, power: "-", accuracy: "-"}
move[145] = {id: 145, name_en: "Bubble", type: type["Water"], category: "Special", pp: 30, power: 40, accuracy: 100}
move[146] = {id: 146, name_en: "Dizzy Punch", type: type["Normal"], category: "Physical", pp: 10, power: 70, accuracy: 100}
move[147] = {id: 147, name_en: "Spore", type: type["Grass"], category: "Status", pp: 15, power: "-", accuracy: 100}
move[148] = {id: 148, name_en: "Flash", type: type["Normal"], category: "Status", pp: 20, power: "-", accuracy: 100}
move[149] = {id: 149, name_en: "Psywave", type: type["Psychic"], category: "Special", pp: 15, power: "-", accuracy: 100}
move[150] = {id: 150, name_en: "Splash", type: type["Normal"], category: "Status", pp: 40, power: "-", accuracy: "-"}
move[151] = {id: 151, name_en: "Acid Armor", type: type["Poison"], category: "Status", pp: 20, power: "-", accuracy: "-"}
move[152] = {id: 152, name_en: "Crabhammer", type: type["Water"], category: "Physical", pp: 10, power: 100, accuracy: 90}
move[153] = {id: 153, name_en: "Explosion", type: type["Normal"], category: "Physical", pp: 5, power: 250, accuracy: 100}
move[154] = {id: 154, name_en: "Fury Swipes", type: type["Normal"], category: "Physical", pp: 15, power: 18, accuracy: 80}
move[155] = {id: 155, name_en: "Bonemerang", type: type["Ground"], category: "Physical", pp: 10, power: 50, accuracy: 90}
move[156] = {id: 156, name_en: "Rest", type: type["Psychic"], category: "Status", pp: 10, power: "-", accuracy: "-"}
move[157] = {id: 157, name_en: "Rock Slide", type: type["Rock"], category: "Physical", pp: 10, power: 75, accuracy: 90}
move[158] = {id: 158, name_en: "Hyper Fang", type: type["Normal"], category: "Physical", pp: 15, power: 80, accuracy: 90}
move[159] = {id: 159, name_en: "Sharpen", type: type["Normal"], category: "Status", pp: 30, power: "-", accuracy: "-"}
move[160] = {id: 160, name_en: "Conversion", type: type["Normal"], category: "Status", pp: 30, power: "-", accuracy: "-"}
move[161] = {id: 161, name_en: "Tri Attack", type: type["Normal"], category: "Special", pp: 10, power: 80, accuracy: 100}
move[162] = {id: 162, name_en: "Super Fang", type: type["Normal"], category: "Physical", pp: 10, power: "-", accuracy: 90}
move[163] = {id: 163, name_en: "Slash", type: type["Normal"], category: "Physical", pp: 20, power: 70, accuracy: 100}
move[164] = {id: 164, name_en: "Substitute", type: type["Normal"], category: "Status", pp: 10, power: "-", accuracy: "-"}
move[165] = {id: 165, name_en: "Struggle", type: type["Normal"], category: "Physical", pp: 1, power: 50, accuracy: "-"}
move[166] = {id: 166, name_en: "Sketch", type: type["Normal"], category: "Status", pp: 1, power: "-", accuracy: "-"}
move[167] = {id: 167, name_en: "Triple Kick", type: type["Fighting"], category: "Physical", pp: 10, power: 10, accuracy: 90}
move[168] = {id: 168, name_en: "Thief", type: type["Dark"], category: "Physical", pp: 25, power: 60, accuracy: 100}
move[169] = {id: 169, name_en: "Spider Web", type: type["Bug"], category: "Status", pp: 10, power: "-", accuracy: 100}
move[170] = {id: 170, name_en: "Mind Reader", type: type["Normal"], category: "Status", pp: 5, power: "-", accuracy: 100}
move[171] = {id: 171, name_en: "Nightmare", type: type["Ghost"], category: "Status", pp: 15, power: "-", accuracy: 100}
move[172] = {id: 172, name_en: "Flame Wheel", type: type["Fire"], category: "Physical", pp: 25, power: 60, accuracy: 100}
move[173] = {id: 173, name_en: "Snore", type: type["Normal"], category: "Special", pp: 15, power: 50, accuracy: 100}
move[174] = {id: 174, name_en: "Curse", type: type["Ghost"], category: "Status", pp: 10, power: "-", accuracy: "-"}
move[175] = {id: 175, name_en: "Flail", type: type["Normal"], category: "Physical", pp: 15, power: "-", accuracy: 100}
move[176] = {id: 176, name_en: "Conversion 2", type: type["Normal"], category: "Status", pp: 30, power: "-", accuracy: 100}
move[177] = {id: 177, name_en: "Aeroblast", type: type["Flying"], category: "Special", pp: 5, power: 100, accuracy: 95}
move[178] = {id: 178, name_en: "Cotton Spore", type: type["Grass"], category: "Status", pp: 40, power: "-", accuracy: 100}
move[179] = {id: 179, name_en: "Reversal", type: type["Fighting"], category: "Physical", pp: 15, power: "-", accuracy: 100}
move[180] = {id: 180, name_en: "Spite", type: type["Ghost"], category: "Status", pp: 10, power: "-", accuracy: 100}
move[181] = {id: 181, name_en: "Powder Snow", type: type["Ice"], category: "Special", pp: 25, power: 40, accuracy: 100}
move[182] = {id: 182, name_en: "Protect", type: type["Normal"], category: "Status", pp: 10, power: "-", accuracy: "-"}
move[183] = {id: 183, name_en: "Mach Punch", type: type["Fighting"], category: "Physical", pp: 30, power: 40, accuracy: 100}
move[184] = {id: 184, name_en: "Scary Face", type: type["Normal"], category: "Status", pp: 10, power: "-", accuracy: 100}
move[185] = {id: 185, name_en: "Feint Attack", type: type["Dark"], category: "Physical", pp: 20, power: 60, accuracy: "-"}
move[186] = {id: 186, name_en: "Sweet Kiss", type: type["Fairy"], category: "Status", pp: 10, power: "-", accuracy: 75}
move[187] = {id: 187, name_en: "Belly Drum", type: type["Normal"], category: "Status", pp: 10, power: "-", accuracy: "-"}
move[188] = {id: 188, name_en: "Sludge Bomb", type: type["Poison"], category: "Special", pp: 10, power: 90, accuracy: 100}
move[189] = {id: 189, name_en: "Mud-Slap", type: type["Ground"], category: "Special", pp: 10, power: 20, accuracy: 100}
move[190] = {id: 190, name_en: "Octazooka", type: type["Water"], category: "Special", pp: 10, power: 65, accuracy: 85}
move[191] = {id: 191, name_en: "Spikes", type: type["Ground"], category: "Status", pp: 20, power: "-", accuracy: "-"}
move[192] = {id: 192, name_en: "Zap Cannon", type: type["Electric"], category: "Special", pp: 5, power: 120, accuracy: 50}
move[193] = {id: 193, name_en: "Foresight", type: type["Normal"], category: "Status", pp: 40, power: "-", accuracy: 100}
move[194] = {id: 194, name_en: "Destiny Bond", type: type["Ghost"], category: "Status", pp: 5, power: "-", accuracy: "-"}
move[195] = {id: 195, name_en: "Perish Song", type: type["Normal"], category: "Status", pp: 5, power: "-", accuracy: "-"}
move[196] = {id: 196, name_en: "Icy Wind", type: type["Ice"], category: "Special", pp: 15, power: 55, accuracy: 95}
move[197] = {id: 197, name_en: "Detect", type: type["Fighting"], category: "Status", pp: 5, power: "-", accuracy: "-"}
move[198] = {id: 198, name_en: "Bone Rush", type: type["Ground"], category: "Physical", pp: 10, power: 25, accuracy: 90}
move[199] = {id: 199, name_en: "Lock-On", type: type["Normal"], category: "Status", pp: 5, power: "-", accuracy: 100}
move[200] = {id: 200, name_en: "Outrage", type: type["Dragon"], category: "Physical", pp: 10, power: 120, accuracy: 100}
move[201] = {id: 201, name_en: "Sandstorm", type: type["Rock"], category: "Status", pp: 10, power: "-", accuracy: "-"}
move[202] = {id: 202, name_en: "Giga Drain", type: type["Grass"], category: "Special", pp: 10, power: 75, accuracy: 100}
move[203] = {id: 203, name_en: "Endure", type: type["Normal"], category: "Status", pp: 10, power: "-", accuracy: "-"}
move[204] = {id: 204, name_en: "Charm", type: type["Fairy"], category: "Status", pp: 20, power: "-", accuracy: 100}
move[205] = {id: 205, name_en: "Rollout", type: type["Rock"], category: "Physical", pp: 20, power: 30, accuracy: 90}
move[206] = {id: 206, name_en: "False Swipe", type: type["Normal"], category: "Physical", pp: 40, power: 40, accuracy: 100}
move[207] = {id: 207, name_en: "Swagger", type: type["Normal"], category: "Status", pp: 15, power: "-", accuracy: 90}
move[208] = {id: 208, name_en: "Milk Drink", type: type["Normal"], category: "Status", pp: 10, power: "-", accuracy: "-"}
move[209] = {id: 209, name_en: "Spark", type: type["Electric"], category: "Physical", pp: 20, power: 65, accuracy: 100}
move[210] = {id: 210, name_en: "Fury Cutter", type: type["Bug"], category: "Physical", pp: 20, power: 40, accuracy: 95}
move[211] = {id: 211, name_en: "Steel Wing", type: type["Steel"], category: "Physical", pp: 25, power: 70, accuracy: 90}
move[212] = {id: 212, name_en: "Mean Look", type: type["Normal"], category: "Status", pp: 5, power: "-", accuracy: 100}
move[213] = {id: 213, name_en: "Attract", type: type["Normal"], category: "Status", pp: 15, power: "-", accuracy: 100}
move[214] = {id: 214, name_en: "Sleep Talk", type: type["Normal"], category: "Status", pp: 10, power: "-", accuracy: "-"}
move[215] = {id: 215, name_en: "Heal Bell", type: type["Normal"], category: "Status", pp: 5, power: "-", accuracy: "-"}
move[216] = {id: 216, name_en: "Return", type: type["Normal"], category: "Physical", pp: 20, power: "-", accuracy: 100}
move[217] = {id: 217, name_en: "Present", type: type["Normal"], category: "Physical", pp: 15, power: "-", accuracy: 90}
move[218] = {id: 218, name_en: "Frustration", type: type["Normal"], category: "Physical", pp: 20, power: "-", accuracy: 100}
move[219] = {id: 219, name_en: "Safeguard", type: type["Normal"], category: "Status", pp: 25, power: "-", accuracy: "-"}
move[220] = {id: 220, name_en: "Pain Split", type: type["Normal"], category: "Status", pp: 20, power: "-", accuracy: 100}
move[221] = {id: 221, name_en: "Sacred Fire", type: type["Fire"], category: "Physical", pp: 5, power: 100, accuracy: 95}
move[222] = {id: 222, name_en: "Magnitude", type: type["Ground"], category: "Physical", pp: 30, power: "-", accuracy: 100}
move[223] = {id: 223, name_en: "Dynamic Punch", type: type["Fighting"], category: "Physical", pp: 5, power: 100, accuracy: 50}
move[224] = {id: 224, name_en: "Megahorn", type: type["Bug"], category: "Physical", pp: 10, power: 120, accuracy: 85}
move[225] = {id: 225, name_en: "Dragon Breath", type: type["Dragon"], category: "Special", pp: 20, power: 60, accuracy: 100}
move[226] = {id: 226, name_en: "Baton Pass", type: type["Normal"], category: "Status", pp: 40, power: "-", accuracy: "-"}
move[227] = {id: 227, name_en: "Encore", type: type["Normal"], category: "Status", pp: 5, power: "-", accuracy: 100}
move[228] = {id: 228, name_en: "Pursuit", type: type["Dark"], category: "Physical", pp: 20, power: 40, accuracy: 100}
move[229] = {id: 229, name_en: "Rapid Spin", type: type["Normal"], category: "Physical", pp: 40, power: 20, accuracy: 100}
move[230] = {id: 230, name_en: "Sweet Scent", type: type["Normal"], category: "Status", pp: 20, power: "-", accuracy: 100}
move[231] = {id: 231, name_en: "Iron Tail", type: type["Steel"], category: "Physical", pp: 15, power: 100, accuracy: 75}
move[232] = {id: 232, name_en: "Metal Claw", type: type["Steel"], category: "Physical", pp: 35, power: 50, accuracy: 95}
move[233] = {id: 233, name_en: "Vital Throw", type: type["Fighting"], category: "Physical", pp: 10, power: 70, accuracy: "-"}
move[234] = {id: 234, name_en: "Morning Sun", type: type["Normal"], category: "Status", pp: 5, power: "-", accuracy: "-"}
move[235] = {id: 235, name_en: "Synthesis", type: type["Grass"], category: "Status", pp: 5, power: "-", accuracy: "-"}
move[236] = {id: 236, name_en: "Moonlight", type: type["Fairy"], category: "Status", pp: 5, power: "-", accuracy: "-"}
move[237] = {id: 237, name_en: "Hidden Power", type: type["Normal"], category: "Special", pp: 15, power: 60, accuracy: 100}
move[238] = {id: 238, name_en: "Cross Chop", type: type["Fighting"], category: "Physical", pp: 5, power: 100, accuracy: 80}
move[239] = {id: 239, name_en: "Twister", type: type["Dragon"], category: "Special", pp: 20, power: 40, accuracy: 100}
move[240] = {id: 240, name_en: "Rain Dance", type: type["Water"], category: "Status", pp: 5, power: "-", accuracy: "-"}
move[241] = {id: 241, name_en: "Sunny Day", type: type["Fire"], category: "Status", pp: 5, power: "-", accuracy: "-"}
move[242] = {id: 242, name_en: "Crunch", type: type["Dark"], category: "Physical", pp: 15, power: 80, accuracy: 100}
move[243] = {id: 243, name_en: "Mirror Coat", type: type["Psychic"], category: "Special", pp: 20, power: "-", accuracy: 100}
move[244] = {id: 244, name_en: "Psych Up", type: type["Normal"], category: "Status", pp: 10, power: "-", accuracy: "-"}
move[245] = {id: 245, name_en: "Extreme Speed", type: type["Normal"], category: "Physical", pp: 5, power: 80, accuracy: 100}
move[246] = {id: 246, name_en: "Ancient Power", type: type["Rock"], category: "Special", pp: 5, power: 60, accuracy: 100}
move[247] = {id: 247, name_en: "Shadow Ball", type: type["Ghost"], category: "Special", pp: 15, power: 80, accuracy: 100}
move[248] = {id: 248, name_en: "Future Sight", type: type["Psychic"], category: "Special", pp: 10, power: 120, accuracy: 100}
move[249] = {id: 249, name_en: "Rock Smash", type: type["Fighting"], category: "Physical", pp: 15, power: 40, accuracy: 100}
move[250] = {id: 250, name_en: "Whirlpool", type: type["Water"], category: "Special", pp: 15, power: 35, accuracy: 85}
move[251] = {id: 251, name_en: "Beat Up", type: type["Dark"], category: "Physical", pp: 10, power: "-", accuracy: 100}
move[252] = {id: 252, name_en: "Fake Out", type: type["Normal"], category: "Physical", pp: 10, power: 40, accuracy: 100}
move[253] = {id: 253, name_en: "Uproar", type: type["Normal"], category: "Special", pp: 10, power: 90, accuracy: 100}
move[254] = {id: 254, name_en: "Stockpile", type: type["Normal"], category: "Status", pp: 20, power: "-", accuracy: "-"}
move[255] = {id: 255, name_en: "Spit Up", type: type["Normal"], category: "Special", pp: 10, power: "-", accuracy: 100}
move[256] = {id: 256, name_en: "Swallow", type: type["Normal"], category: "Status", pp: 10, power: "-", accuracy: "-"}
move[257] = {id: 257, name_en: "Heat Wave", type: type["Fire"], category: "Special", pp: 10, power: 95, accuracy: 90}
move[258] = {id: 258, name_en: "Hail", type: type["Ice"], category: "Status", pp: 10, power: "-", accuracy: "-"}
move[259] = {id: 259, name_en: "Torment", type: type["Dark"], category: "Status", pp: 15, power: "-", accuracy: 100}
move[260] = {id: 260, name_en: "Flatter", type: type["Dark"], category: "Status", pp: 15, power: "-", accuracy: 100}
move[261] = {id: 261, name_en: "Will-O-Wisp", type: type["Fire"], category: "Status", pp: 15, power: "-", accuracy: 85}
move[262] = {id: 262, name_en: "Memento", type: type["Dark"], category: "Status", pp: 10, power: "-", accuracy: 100}
move[263] = {id: 263, name_en: "Facade", type: type["Normal"], category: "Physical", pp: 20, power: 70, accuracy: 100}
move[264] = {id: 264, name_en: "Focus Punch", type: type["Fighting"], category: "Physical", pp: 20, power: 150, accuracy: 100}
move[265] = {id: 265, name_en: "Smelling Salts", type: type["Normal"], category: "Physical", pp: 10, power: 70, accuracy: 100}
move[266] = {id: 266, name_en: "Follow Me", type: type["Normal"], category: "Status", pp: 20, power: "-", accuracy: 100}
move[267] = {id: 267, name_en: "Nature Power", type: type["Normal"], category: "Status", pp: 20, power: "-", accuracy: "-"}
move[268] = {id: 268, name_en: "Charge", type: type["Electric"], category: "Status", pp: 20, power: "-", accuracy: "-"}
move[269] = {id: 269, name_en: "Taunt", type: type["Dark"], category: "Status", pp: 20, power: "-", accuracy: 100}
move[270] = {id: 270, name_en: "Helping Hand", type: type["Normal"], category: "Status", pp: 20, power: "-", accuracy: "-"}
move[271] = {id: 271, name_en: "Trick", type: type["Psychic"], category: "Status", pp: 10, power: "-", accuracy: 100}
move[272] = {id: 272, name_en: "Role Play", type: type["Psychic"], category: "Status", pp: 10, power: "-", accuracy: "-"}
move[273] = {id: 273, name_en: "Wish", type: type["Normal"], category: "Status", pp: 10, power: "-", accuracy: "-"}
move[274] = {id: 274, name_en: "Assist", type: type["Normal"], category: "Status", pp: 20, power: "-", accuracy: "-"}
move[275] = {id: 275, name_en: "Ingrain", type: type["Grass"], category: "Status", pp: 20, power: "-", accuracy: "-"}
move[276] = {id: 276, name_en: "Superpower", type: type["Fighting"], category: "Physical", pp: 5, power: 120, accuracy: 100}
move[277] = {id: 277, name_en: "Magic Coat", type: type["Psychic"], category: "Status", pp: 15, power: "-", accuracy: "-"}
move[278] = {id: 278, name_en: "Recycle", type: type["Normal"], category: "Status", pp: 10, power: "-", accuracy: 100}
move[279] = {id: 279, name_en: "Revenge", type: type["Fighting"], category: "Physical", pp: 10, power: 60, accuracy: 100}
move[280] = {id: 280, name_en: "Brick Break", type: type["Fighting"], category: "Physical", pp: 15, power: 75, accuracy: 100}
move[281] = {id: 281, name_en: "Yawn", type: type["Normal"], category: "Status", pp: 10, power: "-", accuracy: 100}
move[282] = {id: 282, name_en: "Knock Off", type: type["Dark"], category: "Physical", pp: 20, power: 65, accuracy: 100}
move[283] = {id: 283, name_en: "Endeavor", type: type["Normal"], category: "Physical", pp: 5, power: "-", accuracy: 100}
move[284] = {id: 284, name_en: "Eruption", type: type["Fire"], category: "Special", pp: 5, power: "-", accuracy: 100}
move[285] = {id: 285, name_en: "Skill Swap", type: type["Psychic"], category: "Status", pp: 10, power: "-", accuracy: 100}
move[286] = {id: 286, name_en: "Imprison", type: type["Psychic"], category: "Status", pp: 10, power: "-", accuracy: 100}
move[287] = {id: 287, name_en: "Refresh", type: type["Normal"], category: "Status", pp: 20, power: "-", accuracy: 100}
move[288] = {id: 288, name_en: "Grudge", type: type["Ghost"], category: "Status", pp: 5, power: "-", accuracy: 100}
move[289] = {id: 289, name_en: "Snatch", type: type["Dark"], category: "Status", pp: 10, power: "-", accuracy: 100}
move[290] = {id: 290, name_en: "Secret Power", type: type["Normal"], category: "Physical", pp: 20, power: 70, accuracy: 100}
move[291] = {id: 291, name_en: "Dive", type: type["Water"], category: "Physical", pp: 10, power: 80, accuracy: 100}
move[292] = {id: 292, name_en: "Arm Thrust", type: type["Fighting"], category: "Physical", pp: 20, power: 15, accuracy: 100}
move[293] = {id: 293, name_en: "Camouflage", type: type["Normal"], category: "Status", pp: 20, power: "-", accuracy: 100}
move[294] = {id: 294, name_en: "Tail Glow", type: type["Bug"], category: "Status", pp: 20, power: "-", accuracy: 100}
move[295] = {id: 295, name_en: "Luster Purge", type: type["Psychic"], category: "Special", pp: 5, power: 70, accuracy: 100}
move[296] = {id: 296, name_en: "Mist Ball", type: type["Psychic"], category: "Special", pp: 5, power: 70, accuracy: 100}
move[297] = {id: 297, name_en: "Feather Dance", type: type["Flying"], category: "Status", pp: 15, power: "-", accuracy: 100}
move[298] = {id: 298, name_en: "Teeter Dance", type: type["Normal"], category: "Status", pp: 20, power: "-", accuracy: 100}
move[299] = {id: 299, name_en: "Blaze Kick", type: type["Fire"], category: "Physical", pp: 10, power: 85, accuracy: 90}
move[300] = {id: 300, name_en: "Mud Sport", type: type["Ground"], category: "Status", pp: 15, power: "-", accuracy: 100}
move[301] = {id: 301, name_en: "Ice Ball", type: type["Ice"], category: "Physical", pp: 20, power: 30, accuracy: 90}
move[302] = {id: 302, name_en: "Needle Arm", type: type["Grass"], category: "Physical", pp: 15, power: 60, accuracy: 100}
move[303] = {id: 303, name_en: "Slack Off", type: type["Normal"], category: "Status", pp: 10, power: "-", accuracy: 100}
move[304] = {id: 304, name_en: "Hyper Voice", type: type["Normal"], category: "Special", pp: 10, power: 90, accuracy: 100}
move[305] = {id: 305, name_en: "Poison Fang", type: type["Poison"], category: "Physical", pp: 15, power: 50, accuracy: 100}
move[306] = {id: 306, name_en: "Crush Claw", type: type["Normal"], category: "Physical", pp: 10, power: 75, accuracy: 95}
move[307] = {id: 307, name_en: "Blast Burn", type: type["Fire"], category: "Special", pp: 5, power: 150, accuracy: 90}
move[308] = {id: 308, name_en: "Hydro Cannon", type: type["Water"], category: "Special", pp: 5, power: 150, accuracy: 90}
move[309] = {id: 309, name_en: "Meteor Mash", type: type["Steel"], category: "Physical", pp: 10, power: 90, accuracy: 90}
move[310] = {id: 310, name_en: "Astonish", type: type["Ghost"], category: "Physical", pp: 15, power: 30, accuracy: 100}
move[311] = {id: 311, name_en: "Weather Ball", type: type["Normal"], category: "Special", pp: 10, power: 50, accuracy: 100}
move[312] = {id: 312, name_en: "Aromatherapy", type: type["Grass"], category: "Status", pp: 5, power: "-", accuracy: "-"}
move[313] = {id: 313, name_en: "Fake Tears", type: type["Dark"], category: "Status", pp: 20, power: "-", accuracy: 100}
move[314] = {id: 314, name_en: "Air Cutter", type: type["Flying"], category: "Special", pp: 25, power: 60, accuracy: 95}
move[315] = {id: 315, name_en: "Overheat", type: type["Fire"], category: "Special", pp: 5, power: 130, accuracy: 90}
move[316] = {id: 316, name_en: "Odor Sleuth", type: type["Normal"], category: "Status", pp: 40, power: "-", accuracy: 100}
move[317] = {id: 317, name_en: "Rock Tomb", type: type["Rock"], category: "Physical", pp: 15, power: 60, accuracy: 95}
move[318] = {id: 318, name_en: "Silver Wind", type: type["Bug"], category: "Special", pp: 5, power: 60, accuracy: 100}
move[319] = {id: 319, name_en: "Metal Sound", type: type["Steel"], category: "Status", pp: 40, power: "-", accuracy: 85}
move[320] = {id: 320, name_en: "Grass Whistle", type: type["Grass"], category: "Status", pp: 15, power: "-", accuracy: 55}
move[321] = {id: 321, name_en: "Tickle", type: type["Normal"], category: "Status", pp: 20, power: "-", accuracy: 100}
move[322] = {id: 322, name_en: "Cosmic Power", type: type["Psychic"], category: "Status", pp: 20, power: "-", accuracy: "-"}
move[323] = {id: 323, name_en: "Water Spout", type: type["Water"], category: "Special", pp: 5, power: "-", accuracy: 100}
move[324] = {id: 324, name_en: "Signal Beam", type: type["Bug"], category: "Special", pp: 15, power: 75, accuracy: 100}
move[325] = {id: 325, name_en: "Shadow Punch", type: type["Ghost"], category: "Physical", pp: 20, power: 60, accuracy: "-"}
move[326] = {id: 326, name_en: "Extrasensory", type: type["Psychic"], category: "Special", pp: 20, power: 80, accuracy: 100}
move[327] = {id: 327, name_en: "Sky Uppercut", type: type["Fighting"], category: "Physical", pp: 15, power: 85, accuracy: 90}
move[328] = {id: 328, name_en: "Sand Tomb", type: type["Ground"], category: "Physical", pp: 15, power: 35, accuracy: 85}
move[329] = {id: 329, name_en: "Sheer Cold", type: type["Ice"], category: "Special", pp: 5, power: "-", accuracy: "-"}
move[330] = {id: 330, name_en: "Muddy Water", type: type["Water"], category: "Special", pp: 10, power: 90, accuracy: 85}
move[331] = {id: 331, name_en: "Bullet Seed", type: type["Grass"], category: "Physical", pp: 30, power: 25, accuracy: 100}
move[332] = {id: 332, name_en: "Aerial Ace", type: type["Flying"], category: "Physical", pp: 20, power: 60, accuracy: "-"}
move[333] = {id: 333, name_en: "Icicle Spear", type: type["Ice"], category: "Physical", pp: 30, power: 25, accuracy: 100}
move[334] = {id: 334, name_en: "Iron Defense", type: type["Steel"], category: "Status", pp: 15, power: "-", accuracy: "-"}
move[335] = {id: 335, name_en: "Block", type: type["Normal"], category: "Status", pp: 5, power: "-", accuracy: 100}
move[336] = {id: 336, name_en: "Howl", type: type["Normal"], category: "Status", pp: 40, power: "-", accuracy: "-"}
move[337] = {id: 337, name_en: "Dragon Claw", type: type["Dragon"], category: "Physical", pp: 15, power: 80, accuracy: 100}
move[338] = {id: 338, name_en: "Frenzy Plant", type: type["Grass"], category: "Special", pp: 5, power: 150, accuracy: 90}
move[339] = {id: 339, name_en: "Bulk Up", type: type["Fighting"], category: "Status", pp: 20, power: "-", accuracy: "-"}
move[340] = {id: 340, name_en: "Bounce", type: type["Flying"], category: "Physical", pp: 5, power: 85, accuracy: 85}
move[341] = {id: 341, name_en: "Mud Shot", type: type["Ground"], category: "Special", pp: 15, power: 55, accuracy: 95}
move[342] = {id: 342, name_en: "Poison Tail", type: type["Poison"], category: "Physical", pp: 25, power: 50, accuracy: 100}
move[343] = {id: 343, name_en: "Covet", type: type["Normal"], category: "Physical", pp: 25, power: 60, accuracy: 100}
move[344] = {id: 344, name_en: "Volt Tackle", type: type["Electric"], category: "Physical", pp: 15, power: 120, accuracy: 100}
move[345] = {id: 345, name_en: "Magical Leaf", type: type["Grass"], category: "Special", pp: 20, power: 60, accuracy: "-"}
move[346] = {id: 346, name_en: "Water Sport", type: type["Water"], category: "Status", pp: 15, power: "-", accuracy: 100}
move[347] = {id: 347, name_en: "Calm Mind", type: type["Psychic"], category: "Status", pp: 20, power: "-", accuracy: "-"}
move[348] = {id: 348, name_en: "Leaf Blade", type: type["Grass"], category: "Physical", pp: 15, power: 90, accuracy: 100}
move[349] = {id: 349, name_en: "Dragon Dance", type: type["Dragon"], category: "Status", pp: 20, power: "-", accuracy: "-"}
move[350] = {id: 350, name_en: "Rock Blast", type: type["Rock"], category: "Physical", pp: 10, power: 25, accuracy: 90}
move[351] = {id: 351, name_en: "Shock Wave", type: type["Electric"], category: "Special", pp: 20, power: 60, accuracy: "-"}
move[352] = {id: 352, name_en: "Water Pulse", type: type["Water"], category: "Special", pp: 20, power: 60, accuracy: 100}
move[353] = {id: 353, name_en: "Doom Desire", type: type["Steel"], category: "Special", pp: 5, power: 140, accuracy: 100}
move[354] = {id: 354, name_en: "Psycho Boost", type: type["Psychic"], category: "Special", pp: 5, power: 140, accuracy: 90}
move[355] = {id: 355, name_en: "Roost", type: type["Flying"], category: "Status", pp: 10, power: "-", accuracy: "-"}
move[356] = {id: 356, name_en: "Gravity", type: type["Psychic"], category: "Status", pp: 5, power: "-", accuracy: "-"}
move[357] = {id: 357, name_en: "Miracle Eye", type: type["Psychic"], category: "Status", pp: 40, power: "-", accuracy: "-"}
move[358] = {id: 358, name_en: "Wake-Up Slap", type: type["Fighting"], category: "Physical", pp: 10, power: 70, accuracy: 100}
move[359] = {id: 359, name_en: "Hammer Arm", type: type["Fighting"], category: "Physical", pp: 10, power: 100, accuracy: 90}
move[360] = {id: 360, name_en: "Gyro Ball", type: type["Steel"], category: "Physical", pp: 5, power: "-", accuracy: 100}
move[361] = {id: 361, name_en: "Healing Wish", type: type["Psychic"], category: "Status", pp: 10, power: "-", accuracy: "-"}
move[362] = {id: 362, name_en: "Brine", type: type["Water"], category: "Special", pp: 10, power: 65, accuracy: 100}
move[363] = {id: 363, name_en: "Natural Gift", type: type["Normal"], category: "Physical", pp: 15, power: "-", accuracy: 100}
move[364] = {id: 364, name_en: "Feint", type: type["Normal"], category: "Physical", pp: 10, power: 30, accuracy: 100}
move[365] = {id: 365, name_en: "Pluck", type: type["Flying"], category: "Physical", pp: 20, power: 60, accuracy: 100}
move[366] = {id: 366, name_en: "Tailwind", type: type["Flying"], category: "Status", pp: 15, power: "-", accuracy: "-"}
move[367] = {id: 367, name_en: "Acupressure", type: type["Normal"], category: "Status", pp: 30, power: "-", accuracy: "-"}
move[368] = {id: 368, name_en: "Metal Burst", type: type["Steel"], category: "Physical", pp: 10, power: "-", accuracy: 100}
move[369] = {id: 369, name_en: "U-turn", type: type["Bug"], category: "Physical", pp: 20, power: 70, accuracy: 100}
move[370] = {id: 370, name_en: "Close Combat", type: type["Fighting"], category: "Physical", pp: 5, power: 120, accuracy: 100}
move[371] = {id: 371, name_en: "Payback", type: type["Dark"], category: "Physical", pp: 10, power: 50, accuracy: 100}
move[372] = {id: 372, name_en: "Assurance", type: type["Dark"], category: "Physical", pp: 10, power: 60, accuracy: 100}
move[373] = {id: 373, name_en: "Embargo", type: type["Dark"], category: "Status", pp: 15, power: "-", accuracy: 100}
move[374] = {id: 374, name_en: "Fling", type: type["Dark"], category: "Physical", pp: 10, power: "-", accuracy: 100}
move[375] = {id: 375, name_en: "Psycho Shift", type: type["Psychic"], category: "Status", pp: 10, power: "-", accuracy: 100}
move[376] = {id: 376, name_en: "Trump Card", type: type["Normal"], category: "Special", pp: 5, power: "-", accuracy: "-"}
move[377] = {id: 377, name_en: "Heal Block", type: type["Psychic"], category: "Status", pp: 15, power: "-", accuracy: 100}
move[378] = {id: 378, name_en: "Wring Out", type: type["Normal"], category: "Special", pp: 5, power: "-", accuracy: 100}
move[379] = {id: 379, name_en: "Power Trick", type: type["Psychic"], category: "Status", pp: 10, power: "-", accuracy: "-"}
move[380] = {id: 380, name_en: "Gastro Acid", type: type["Poison"], category: "Status", pp: 10, power: "-", accuracy: 100}
move[381] = {id: 381, name_en: "Lucky Chant", type: type["Normal"], category: "Status", pp: 30, power: "-", accuracy: "-"}
move[382] = {id: 382, name_en: "Me First", type: type["Normal"], category: "Status", pp: 20, power: "-", accuracy: "-"}
move[383] = {id: 383, name_en: "Copycat", type: type["Normal"], category: "Status", pp: 20, power: "-", accuracy: "-"}
move[384] = {id: 384, name_en: "Power Swap", type: type["Psychic"], category: "Status", pp: 10, power: "-", accuracy: "-"}
move[385] = {id: 385, name_en: "Guard Swap", type: type["Psychic"], category: "Status", pp: 10, power: "-", accuracy: "-"}
move[386] = {id: 386, name_en: "Punishment", type: type["Dark"], category: "Physical", pp: 5, power: "-", accuracy: 100}
move[387] = {id: 387, name_en: "Last Resort", type: type["Normal"], category: "Physical", pp: 5, power: 140, accuracy: 100}
move[388] = {id: 388, name_en: "Worry Seed", type: type["Grass"], category: "Status", pp: 10, power: "-", accuracy: 100}
move[389] = {id: 389, name_en: "Sucker Punch", type: type["Dark"], category: "Physical", pp: 5, power: 80, accuracy: 100}
move[390] = {id: 390, name_en: "Toxic Spikes", type: type["Poison"], category: "Status", pp: 20, power: "-", accuracy: "-"}
move[391] = {id: 391, name_en: "Heart Swap", type: type["Psychic"], category: "Status", pp: 10, power: "-", accuracy: "-"}
move[392] = {id: 392, name_en: "Aqua Ring", type: type["Water"], category: "Status", pp: 20, power: "-", accuracy: "-"}
move[393] = {id: 393, name_en: "Magnet Rise", type: type["Electric"], category: "Status", pp: 10, power: "-", accuracy: "-"}
move[394] = {id: 394, name_en: "Flare Blitz", type: type["Fire"], category: "Physical", pp: 15, power: 120, accuracy: 100}
move[395] = {id: 395, name_en: "Force Palm", type: type["Fighting"], category: "Physical", pp: 10, power: 60, accuracy: 100}
move[396] = {id: 396, name_en: "Aura Sphere", type: type["Fighting"], category: "Special", pp: 20, power: 80, accuracy: "-"}
move[397] = {id: 397, name_en: "Rock Polish", type: type["Rock"], category: "Status", pp: 20, power: "-", accuracy: "-"}
move[398] = {id: 398, name_en: "Poison Jab", type: type["Poison"], category: "Physical", pp: 20, power: 80, accuracy: 100}
move[399] = {id: 399, name_en: "Dark Pulse", type: type["Dark"], category: "Special", pp: 15, power: 80, accuracy: 100}
move[400] = {id: 400, name_en: "Night Slash", type: type["Dark"], category: "Physical", pp: 15, power: 70, accuracy: 100}
move[401] = {id: 401, name_en: "Aqua Tail", type: type["Water"], category: "Physical", pp: 10, power: 90, accuracy: 90}
move[402] = {id: 402, name_en: "Seed Bomb", type: type["Grass"], category: "Physical", pp: 15, power: 80, accuracy: 100}
move[403] = {id: 403, name_en: "Air Slash", type: type["Flying"], category: "Special", pp: 15, power: 75, accuracy: 95}
move[404] = {id: 404, name_en: "X-Scissor", type: type["Bug"], category: "Physical", pp: 15, power: 80, accuracy: 100}
move[405] = {id: 405, name_en: "Bug Buzz", type: type["Bug"], category: "Special", pp: 10, power: 90, accuracy: 100}
move[406] = {id: 406, name_en: "Dragon Pulse", type: type["Dragon"], category: "Special", pp: 10, power: 85, accuracy: 100}
move[407] = {id: 407, name_en: "Dragon Rush", type: type["Dragon"], category: "Physical", pp: 10, power: 100, accuracy: 75}
move[408] = {id: 408, name_en: "Power Gem", type: type["Rock"], category: "Special", pp: 20, power: 80, accuracy: 100}
move[409] = {id: 409, name_en: "Drain Punch", type: type["Fighting"], category: "Physical", pp: 10, power: 75, accuracy: 100}
move[410] = {id: 410, name_en: "Vacuum Wave", type: type["Fighting"], category: "Special", pp: 30, power: 40, accuracy: 100}
move[411] = {id: 411, name_en: "Focus Blast", type: type["Fighting"], category: "Special", pp: 5, power: 120, accuracy: 70}
move[412] = {id: 412, name_en: "Energy Ball", type: type["Grass"], category: "Special", pp: 10, power: 90, accuracy: 100}
move[413] = {id: 413, name_en: "Brave Bird", type: type["Flying"], category: "Physical", pp: 15, power: 120, accuracy: 100}
move[414] = {id: 414, name_en: "Earth Power", type: type["Ground"], category: "Special", pp: 10, power: 90, accuracy: 100}
move[415] = {id: 415, name_en: "Switcheroo", type: type["Dark"], category: "Status", pp: 10, power: "-", accuracy: 100}
move[416] = {id: 416, name_en: "Giga Impact", type: type["Normal"], category: "Physical", pp: 5, power: 150, accuracy: 90}
move[417] = {id: 417, name_en: "Nasty Plot", type: type["Dark"], category: "Status", pp: 20, power: "-", accuracy: "-"}
move[418] = {id: 418, name_en: "Bullet Punch", type: type["Steel"], category: "Physical", pp: 30, power: 40, accuracy: 100}
move[419] = {id: 419, name_en: "Avalanche", type: type["Ice"], category: "Physical", pp: 10, power: 60, accuracy: 100}
move[420] = {id: 420, name_en: "Ice Shard", type: type["Ice"], category: "Physical", pp: 30, power: 40, accuracy: 100}
move[421] = {id: 421, name_en: "Shadow Claw", type: type["Ghost"], category: "Physical", pp: 15, power: 70, accuracy: 100}
move[422] = {id: 422, name_en: "Thunder Fang", type: type["Electric"], category: "Physical", pp: 15, power: 65, accuracy: 95}
move[423] = {id: 423, name_en: "Ice Fang", type: type["Ice"], category: "Physical", pp: 15, power: 65, accuracy: 95}
move[424] = {id: 424, name_en: "Fire Fang", type: type["Fire"], category: "Physical", pp: 15, power: 65, accuracy: 95}
move[425] = {id: 425, name_en: "Shadow Sneak", type: type["Ghost"], category: "Physical", pp: 30, power: 40, accuracy: 100}
move[426] = {id: 426, name_en: "Mud Bomb", type: type["Ground"], category: "Special", pp: 10, power: 65, accuracy: 85}
move[427] = {id: 427, name_en: "Psycho Cut", type: type["Psychic"], category: "Physical", pp: 20, power: 70, accuracy: 100}
move[428] = {id: 428, name_en: "Zen Headbutt", type: type["Psychic"], category: "Physical", pp: 15, power: 80, accuracy: 90}
move[429] = {id: 429, name_en: "Mirror Shot", type: type["Steel"], category: "Special", pp: 10, power: 65, accuracy: 85}
move[430] = {id: 430, name_en: "Flash Cannon", type: type["Steel"], category: "Special", pp: 10, power: 80, accuracy: 100}
move[431] = {id: 431, name_en: "Rock Climb", type: type["Normal"], category: "Physical", pp: 20, power: 90, accuracy: 85}
move[432] = {id: 432, name_en: "Defog", type: type["Flying"], category: "Status", pp: 15, power: "-", accuracy: "-"}
move[433] = {id: 433, name_en: "Trick Room", type: type["Psychic"], category: "Status", pp: 5, power: "-", accuracy: "-"}
move[434] = {id: 434, name_en: "Draco Meteor", type: type["Dragon"], category: "Special", pp: 5, power: 130, accuracy: 90}
move[435] = {id: 435, name_en: "Discharge", type: type["Electric"], category: "Special", pp: 15, power: 80, accuracy: 100}
move[436] = {id: 436, name_en: "Lava Plume", type: type["Fire"], category: "Special", pp: 15, power: 80, accuracy: 100}
move[437] = {id: 437, name_en: "Leaf Storm", type: type["Grass"], category: "Special", pp: 5, power: 130, accuracy: 90}
move[438] = {id: 438, name_en: "Power Whip", type: type["Grass"], category: "Physical", pp: 10, power: 120, accuracy: 85}
move[439] = {id: 439, name_en: "Rock Wrecker", type: type["Rock"], category: "Physical", pp: 5, power: 150, accuracy: 90}
move[440] = {id: 440, name_en: "Cross Poison", type: type["Poison"], category: "Physical", pp: 20, power: 70, accuracy: 100}
move[441] = {id: 441, name_en: "Gunk Shot", type: type["Poison"], category: "Physical", pp: 5, power: 120, accuracy: 80}
move[442] = {id: 442, name_en: "Iron Head", type: type["Steel"], category: "Physical", pp: 15, power: 80, accuracy: 100}
move[443] = {id: 443, name_en: "Magnet Bomb", type: type["Steel"], category: "Physical", pp: 20, power: 60, accuracy: "-"}
move[444] = {id: 444, name_en: "Stone Edge", type: type["Rock"], category: "Physical", pp: 5, power: 100, accuracy: 80}
move[445] = {id: 445, name_en: "Captivate", type: type["Normal"], category: "Status", pp: 20, power: "-", accuracy: 100}
move[446] = {id: 446, name_en: "Stealth Rock", type: type["Rock"], category: "Status", pp: 20, power: "-", accuracy: "-"}
move[447] = {id: 447, name_en: "Grass Knot", type: type["Grass"], category: "Special", pp: 20, power: "-", accuracy: 100}
move[448] = {id: 448, name_en: "Chatter", type: type["Flying"], category: "Special", pp: 20, power: 65, accuracy: 100}
move[449] = {id: 449, name_en: "Judgment", type: type["Normal"], category: "Special", pp: 10, power: 100, accuracy: 100}
move[450] = {id: 450, name_en: "Bug Bite", type: type["Bug"], category: "Physical", pp: 20, power: 60, accuracy: 100}
move[451] = {id: 451, name_en: "Charge Beam", type: type["Electric"], category: "Special", pp: 10, power: 50, accuracy: 90}
move[452] = {id: 452, name_en: "Wood Hammer", type: type["Grass"], category: "Physical", pp: 15, power: 120, accuracy: 100}
move[453] = {id: 453, name_en: "Aqua Jet", type: type["Water"], category: "Physical", pp: 20, power: 40, accuracy: 100}
move[454] = {id: 454, name_en: "Attack Order", type: type["Bug"], category: "Physical", pp: 15, power: 90, accuracy: 100}
move[455] = {id: 455, name_en: "Defend Order", type: type["Bug"], category: "Status", pp: 10, power: "-", accuracy: "-"}
move[456] = {id: 456, name_en: "Heal Order", type: type["Bug"], category: "Status", pp: 10, power: "-", accuracy: "-"}
move[457] = {id: 457, name_en: "Head Smash", type: type["Rock"], category: "Physical", pp: 5, power: 150, accuracy: 80}
move[458] = {id: 458, name_en: "Double Hit", type: type["Normal"], category: "Physical", pp: 10, power: 35, accuracy: 90}
move[459] = {id: 459, name_en: "Roar of Time", type: type["Dragon"], category: "Special", pp: 5, power: 150, accuracy: 90}
move[460] = {id: 460, name_en: "Spacial Rend", type: type["Dragon"], category: "Special", pp: 5, power: 100, accuracy: 95}
move[461] = {id: 461, name_en: "Lunar Dance", type: type["Psychic"], category: "Status", pp: 10, power: "-", accuracy: "-"}
move[462] = {id: 462, name_en: "Crush Grip", type: type["Normal"], category: "Physical", pp: 5, power: "-", accuracy: 100}
move[463] = {id: 463, name_en: "Magma Storm", type: type["Fire"], category: "Special", pp: 5, power: 100, accuracy: 75}
move[464] = {id: 464, name_en: "Dark Void", type: type["Dark"], category: "Status", pp: 10, power: "-", accuracy: 80}
move[465] = {id: 465, name_en: "Seed Flare", type: type["Grass"], category: "Special", pp: 5, power: 120, accuracy: 85}
move[466] = {id: 466, name_en: "Ominous Wind", type: type["Ghost"], category: "Special", pp: 5, power: 60, accuracy: 100}
move[467] = {id: 467, name_en: "Shadow Force", type: type["Ghost"], category: "Physical", pp: 5, power: 120, accuracy: 100}
move[468] = {id: 468, name_en: "Hone Claws", type: type["Dark"], category: "Status", pp: 15, power: "-", accuracy: "-"}
move[469] = {id: 469, name_en: "Wide Guard", type: type["Rock"], category: "Status", pp: 10, power: "-", accuracy: "-"}
move[470] = {id: 470, name_en: "Guard Split", type: type["Psychic"], category: "Status", pp: 10, power: "-", accuracy: "-"}
move[471] = {id: 471, name_en: "Power Split", type: type["Psychic"], category: "Status", pp: 10, power: "-", accuracy: "-"}
move[472] = {id: 472, name_en: "Wonder Room", type: type["Psychic"], category: "Status", pp: 10, power: "-", accuracy: "-"}
move[473] = {id: 473, name_en: "Psyshock", type: type["Psychic"], category: "Special", pp: 10, power: 80, accuracy: 100}
move[474] = {id: 474, name_en: "Venoshock", type: type["Poison"], category: "Special", pp: 10, power: 65, accuracy: 100}
move[475] = {id: 475, name_en: "Autotomize", type: type["Steel"], category: "Status", pp: 15, power: "-", accuracy: "-"}
move[476] = {id: 476, name_en: "Rage Powder", type: type["Bug"], category: "Status", pp: 20, power: "-", accuracy: "-"}
move[477] = {id: 477, name_en: "Telekinesis", type: type["Psychic"], category: "Status", pp: 15, power: "-", accuracy: "-"}
move[478] = {id: 478, name_en: "Magic Room", type: type["Psychic"], category: "Status", pp: 10, power: "-", accuracy: "-"}
move[479] = {id: 479, name_en: "Smack Down", type: type["Rock"], category: "Physical", pp: 15, power: 50, accuracy: 100}
move[480] = {id: 480, name_en: "Storm Throw", type: type["Fighting"], category: "Physical", pp: 10, power: 60, accuracy: 100}
move[481] = {id: 481, name_en: "Flame Burst", type: type["Fire"], category: "Special", pp: 15, power: 70, accuracy: 100}
move[482] = {id: 482, name_en: "Sludge Wave", type: type["Poison"], category: "Special", pp: 10, power: 95, accuracy: 100}
move[483] = {id: 483, name_en: "Quiver Dance", type: type["Bug"], category: "Status", pp: 20, power: "-", accuracy: "-"}
move[484] = {id: 484, name_en: "Heavy Slam", type: type["Steel"], category: "Physical", pp: 10, power: "-", accuracy: 100}
move[485] = {id: 485, name_en: "Synchronoise", type: type["Psychic"], category: "Special", pp: 15, power: 120, accuracy: 100}
move[486] = {id: 486, name_en: "Electro Ball", type: type["Electric"], category: "Special", pp: 10, power: "-", accuracy: 100}
move[487] = {id: 487, name_en: "Soak", type: type["Water"], category: "Status", pp: 20, power: "-", accuracy: 100}
move[488] = {id: 488, name_en: "Flame Charge", type: type["Fire"], category: "Physical", pp: 20, power: 50, accuracy: 100}
move[489] = {id: 489, name_en: "Coil", type: type["Poison"], category: "Status", pp: 20, power: "-", accuracy: "-"}
move[490] = {id: 490, name_en: "Low Sweep", type: type["Fighting"], category: "Physical", pp: 20, power: 65, accuracy: 100}
move[491] = {id: 491, name_en: "Acid Spray", type: type["Poison"], category: "Special", pp: 20, power: 40, accuracy: 100}
move[492] = {id: 492, name_en: "Foul Play", type: type["Dark"], category: "Physical", pp: 15, power: 95, accuracy: 100}
move[493] = {id: 493, name_en: "Simple Beam", type: type["Normal"], category: "Status", pp: 15, power: "-", accuracy: 100}
move[494] = {id: 494, name_en: "Entrainment", type: type["Normal"], category: "Status", pp: 15, power: "-", accuracy: 100}
move[495] = {id: 495, name_en: "After You", type: type["Normal"], category: "Status", pp: 15, power: "-", accuracy: "-"}
move[496] = {id: 496, name_en: "Round", type: type["Normal"], category: "Special", pp: 15, power: 60, accuracy: 100}
move[497] = {id: 497, name_en: "Echoed Voice", type: type["Normal"], category: "Special", pp: 15, power: 40, accuracy: 100}
move[498] = {id: 498, name_en: "Chip Away", type: type["Normal"], category: "Physical", pp: 20, power: 70, accuracy: 100}
move[499] = {id: 499, name_en: "Clear Smog", type: type["Poison"], category: "Special", pp: 15, power: 50, accuracy: "-"}
move[500] = {id: 500, name_en: "Stored Power", type: type["Psychic"], category: "Special", pp: 10, power: 20, accuracy: 100}
move[501] = {id: 501, name_en: "Quick Guard", type: type["Fighting"], category: "Status", pp: 15, power: "-", accuracy: "-"}
move[502] = {id: 502, name_en: "Ally Switch", type: type["Psychic"], category: "Status", pp: 15, power: "-", accuracy: "-"}
move[503] = {id: 503, name_en: "Scald", type: type["Water"], category: "Special", pp: 15, power: 80, accuracy: 100}
move[504] = {id: 504, name_en: "Shell Smash", type: type["Normal"], category: "Status", pp: 15, power: "-", accuracy: "-"}
move[505] = {id: 505, name_en: "Heal Pulse", type: type["Psychic"], category: "Status", pp: 10, power: "-", accuracy: "-"}
move[506] = {id: 506, name_en: "Hex", type: type["Ghost"], category: "Special", pp: 10, power: 65, accuracy: 100}
move[507] = {id: 507, name_en: "Sky Drop", type: type["Flying"], category: "Physical", pp: 10, power: 60, accuracy: 100}
move[508] = {id: 508, name_en: "Shift Gear", type: type["Steel"], category: "Status", pp: 10, power: "-", accuracy: "-"}
move[509] = {id: 509, name_en: "Circle Throw", type: type["Fighting"], category: "Physical", pp: 10, power: 60, accuracy: 90}
move[510] = {id: 510, name_en: "Incinerate", type: type["Fire"], category: "Special", pp: 15, power: 60, accuracy: 100}
move[511] = {id: 511, name_en: "Quash", type: type["Dark"], category: "Status", pp: 15, power: "-", accuracy: 100}
move[512] = {id: 512, name_en: "Acrobatics", type: type["Flying"], category: "Physical", pp: 15, power: 55, accuracy: 100}
move[513] = {id: 513, name_en: "Reflect Type", type: type["Normal"], category: "Status", pp: 15, power: "-", accuracy: "-"}
move[514] = {id: 514, name_en: "Retaliate", type: type["Normal"], category: "Physical", pp: 5, power: 70, accuracy: 100}
move[515] = {id: 515, name_en: "Final Gambit", type: type["Fighting"], category: "Special", pp: 5, power: "-", accuracy: 100}
move[516] = {id: 516, name_en: "Bestow", type: type["Normal"], category: "Status", pp: 15, power: "-", accuracy: "-"}
move[517] = {id: 517, name_en: "Inferno", type: type["Fire"], category: "Special", pp: 5, power: 100, accuracy: 50}
move[518] = {id: 518, name_en: "Water Pledge", type: type["Water"], category: "Special", pp: 10, power: 80, accuracy: 100}
move[519] = {id: 519, name_en: "Fire Pledge", type: type["Fire"], category: "Special", pp: 10, power: 80, accuracy: 100}
move[520] = {id: 520, name_en: "Grass Pledge", type: type["Grass"], category: "Special", pp: 10, power: 80, accuracy: 100}
move[521] = {id: 521, name_en: "Volt Switch", type: type["Electric"], category: "Special", pp: 20, power: 70, accuracy: 100}
move[522] = {id: 522, name_en: "Struggle Bug", type: type["Bug"], category: "Special", pp: 20, power: 50, accuracy: 100}
move[523] = {id: 523, name_en: "Bulldoze", type: type["Ground"], category: "Physical", pp: 20, power: 60, accuracy: 100}
move[524] = {id: 524, name_en: "Frost Breath", type: type["Ice"], category: "Special", pp: 10, power: 60, accuracy: 90}
move[525] = {id: 525, name_en: "Dragon Tail", type: type["Dragon"], category: "Physical", pp: 10, power: 60, accuracy: 90}
move[526] = {id: 526, name_en: "Work Up", type: type["Normal"], category: "Status", pp: 30, power: "-", accuracy: "-"}
move[527] = {id: 527, name_en: "Electroweb", type: type["Electric"], category: "Special", pp: 15, power: 55, accuracy: 95}
move[528] = {id: 528, name_en: "Wild Charge", type: type["Electric"], category: "Physical", pp: 15, power: 90, accuracy: 100}
move[529] = {id: 529, name_en: "Drill Run", type: type["Ground"], category: "Physical", pp: 10, power: 80, accuracy: 95}
move[530] = {id: 530, name_en: "Dual Chop", type: type["Dragon"], category: "Physical", pp: 15, power: 40, accuracy: 90}
move[531] = {id: 531, name_en: "Heart Stamp", type: type["Psychic"], category: "Physical", pp: 25, power: 60, accuracy: 100}
move[532] = {id: 532, name_en: "Horn Leech", type: type["Grass"], category: "Physical", pp: 10, power: 75, accuracy: 100}
move[533] = {id: 533, name_en: "Sacred Sword", type: type["Fighting"], category: "Physical", pp: 15, power: 90, accuracy: 100}
move[534] = {id: 534, name_en: "Razor Shell", type: type["Water"], category: "Physical", pp: 10, power: 75, accuracy: 95}
move[535] = {id: 535, name_en: "Heat Crash", type: type["Fire"], category: "Physical", pp: 10, power: "-", accuracy: 100}
move[536] = {id: 536, name_en: "Leaf Tornado", type: type["Grass"], category: "Special", pp: 10, power: 65, accuracy: 90}
move[537] = {id: 537, name_en: "Steamroller", type: type["Bug"], category: "Physical", pp: 20, power: 65, accuracy: 100}
move[538] = {id: 538, name_en: "Cotton Guard", type: type["Grass"], category: "Status", pp: 10, power: "-", accuracy: "-"}
move[539] = {id: 539, name_en: "Night Daze", type: type["Dark"], category: "Special", pp: 10, power: 85, accuracy: 95}
move[540] = {id: 540, name_en: "Psystrike", type: type["Psychic"], category: "Special", pp: 10, power: 100, accuracy: 100}
move[541] = {id: 541, name_en: "Tail Slap", type: type["Normal"], category: "Physical", pp: 10, power: 25, accuracy: 85}
move[542] = {id: 542, name_en: "Hurricane", type: type["Flying"], category: "Special", pp: 10, power: 110, accuracy: 70}
move[543] = {id: 543, name_en: "Head Charge", type: type["Normal"], category: "Physical", pp: 15, power: 120, accuracy: 100}
move[544] = {id: 544, name_en: "Gear Grind", type: type["Steel"], category: "Physical", pp: 15, power: 50, accuracy: 85}
move[545] = {id: 545, name_en: "Searing Shot", type: type["Fire"], category: "Special", pp: 5, power: 100, accuracy: 100}
move[546] = {id: 546, name_en: "Techno Blast", type: type["Normal"], category: "Special", pp: 5, power: 120, accuracy: 100}
move[547] = {id: 547, name_en: "Relic Song", type: type["Normal"], category: "Special", pp: 10, power: 75, accuracy: 100}
move[548] = {id: 548, name_en: "Secret Sword", type: type["Fighting"], category: "Special", pp: 10, power: 85, accuracy: 100}
move[549] = {id: 549, name_en: "Glaciate", type: type["Ice"], category: "Special", pp: 10, power: 65, accuracy: 95}
move[550] = {id: 550, name_en: "Bolt Strike", type: type["Electric"], category: "Physical", pp: 5, power: 130, accuracy: 85}
move[551] = {id: 551, name_en: "Blue Flare", type: type["Fire"], category: "Special", pp: 5, power: 130, accuracy: 85}
move[552] = {id: 552, name_en: "Fiery Dance", type: type["Fire"], category: "Special", pp: 10, power: 80, accuracy: 100}
move[553] = {id: 553, name_en: "Freeze Shock", type: type["Ice"], category: "Physical", pp: 5, power: 140, accuracy: 90}
move[554] = {id: 554, name_en: "Ice Burn", type: type["Ice"], category: "Special", pp: 5, power: 140, accuracy: 90}
move[555] = {id: 555, name_en: "Snarl", type: type["Dark"], category: "Special", pp: 15, power: 55, accuracy: 95}
move[556] = {id: 556, name_en: "Icicle Crash", type: type["Ice"], category: "Physical", pp: 10, power: 85, accuracy: 90}
move[557] = {id: 557, name_en: "V-create", type: type["Fire"], category: "Physical", pp: 5, power: 180, accuracy: 95}
move[558] = {id: 558, name_en: "Fusion Flare", type: type["Fire"], category: "Special", pp: 5, power: 100, accuracy: 100}
move[559] = {id: 559, name_en: "Fusion Bolt", type: type["Electric"], category: "Physical", pp: 5, power: 100, accuracy: 100}
move[560] = {id: 560, name_en: "Flying Press", type: type["Fighting"], category: "Physical", pp: 10, power: 80, accuracy: 95}
move[561] = {id: 561, name_en: "Mat Block", type: type["Fighting"], category: "Status", pp: 10, power: "-", accuracy: "-"}
move[562] = {id: 562, name_en: "Belch", type: type["Poison"], category: "Special", pp: 10, power: 120, accuracy: 90}
move[563] = {id: 563, name_en: "Rototiller", type: type["Ground"], category: "Status", pp: 10, power: "-", accuracy: "-"}
move[564] = {id: 564, name_en: "Sticky Web", type: type["Bug"], category: "Status", pp: 20, power: "-", accuracy: "-"}
move[565] = {id: 565, name_en: "Fell Stinger", type: type["Bug"], category: "Physical", pp: 25, power: 30, accuracy: 100}
move[566] = {id: 566, name_en: "Phantom Force", type: type["Ghost"], category: "Physical", pp: 10, power: 90, accuracy: 100}
move[567] = {id: 567, name_en: "Trick-or-Treat", type: type["Ghost"], category: "Status", pp: 20, power: "-", accuracy: 100}
move[568] = {id: 568, name_en: "Noble Roar", type: type["Normal"], category: "Status", pp: 30, power: "-", accuracy: 100}
move[569] = {id: 569, name_en: "Ion Deluge", type: type["Electric"], category: "Status", pp: 25, power: "-", accuracy: "-"}
move[570] = {id: 570, name_en: "Parabolic Charge", type: type["Electric"], category: "Special", pp: 20, power: 50, accuracy: 100}
move[571] = {id: 571, name_en: "Forest's Curse", type: type["Grass"], category: "Status", pp: 20, power: "-", accuracy: 100}
move[572] = {id: 572, name_en: "Petal Blizzard", type: type["Grass"], category: "Physical", pp: 15, power: 90, accuracy: 100}
move[573] = {id: 573, name_en: "Freeze-Dry", type: type["Ice"], category: "Special", pp: 20, power: 70, accuracy: 100}
move[574] = {id: 574, name_en: "Disarming Voice", type: type["Fairy"], category: "Special", pp: 15, power: 40, accuracy: "-"}
move[575] = {id: 575, name_en: "Parting Shot", type: type["Dark"], category: "Status", pp: 20, power: "-", accuracy: 100}
move[576] = {id: 576, name_en: "Topsy-Turvy", type: type["Dark"], category: "Status", pp: 20, power: "-", accuracy: 100}
move[577] = {id: 577, name_en: "Draining Kiss", type: type["Fairy"], category: "Special", pp: 10, power: 50, accuracy: 100}
move[578] = {id: 578, name_en: "Crafty Shield", type: type["Fairy"], category: "Status", pp: 10, power: "-", accuracy: "-"}
move[579] = {id: 579, name_en: "Flower Shield", type: type["Fairy"], category: "Status", pp: 10, power: "-", accuracy: "-"}
move[580] = {id: 580, name_en: "Grassy Terrain", type: type["Grass"], category: "Status", pp: 10, power: "-", accuracy: "-"}
move[581] = {id: 581, name_en: "Misty Terrain", type: type["Fairy"], category: "Status", pp: 10, power: "-", accuracy: "-"}
move[582] = {id: 582, name_en: "Electrify", type: type["Electric"], category: "Status", pp: 20, power: "-", accuracy: "-"}
move[583] = {id: 583, name_en: "Play Rough", type: type["Fairy"], category: "Physical", pp: 10, power: 90, accuracy: 90}
move[584] = {id: 584, name_en: "Fairy Wind", type: type["Fairy"], category: "Special", pp: 30, power: 40, accuracy: "-"}
move[585] = {id: 585, name_en: "Moonblast", type: type["Fairy"], category: "Special", pp: 15, power: 95, accuracy: 100}
move[586] = {id: 586, name_en: "Boomburst", type: type["Normal"], category: "Special", pp: 10, power: 140, accuracy: 100}
move[587] = {id: 587, name_en: "Fairy Lock", type: type["Fairy"], category: "Status", pp: 10, power: "-", accuracy: "-"}
move[588] = {id: 588, name_en: "King's Shield", type: type["Steel"], category: "Status", pp: 10, power: "-", accuracy: "-"}
move[589] = {id: 589, name_en: "Play Nice", type: type["Normal"], category: "Status", pp: 20, power: "-", accuracy: "-"}
move[590] = {id: 590, name_en: "Confide", type: type["Normal"], category: "Status", pp: 20, power: "-", accuracy: "-"}
move[591] = {id: 591, name_en: "Diamond Storm", type: type["Rock"], category: "Physical", pp: 5, power: 100, accuracy: 95}
move[592] = {id: 592, name_en: "Steam Eruption", type: type["Water"], category: "Special", pp: 5, power: 110, accuracy: 95}
move[593] = {id: 593, name_en: "Hyperspace Hole", type: type["Psychic"], category: "Special", pp: 5, power: 80, accuracy: "-"}
move[594] = {id: 594, name_en: "Water Shuriken", type: type["Water"], category: "Physical", pp: 20, power: 15, accuracy: 100}
move[595] = {id: 595, name_en: "Mystical Fire", type: type["Fire"], category: "Special", pp: 10, power: 65, accuracy: 100}
move[596] = {id: 596, name_en: "Spiky Shield", type: type["Grass"], category: "Status", pp: 10, power: "-", accuracy: "-"}
move[597] = {id: 597, name_en: "Aromatic Mist", type: type["Fairy"], category: "Status", pp: 20, power: "-", accuracy: "-"}
move[598] = {id: 598, name_en: "Eerie Impulse", type: type["Electric"], category: "Status", pp: 15, power: "-", accuracy: 100}
move[599] = {id: 599, name_en: "Venom Drench", type: type["Poison"], category: "Status", pp: 20, power: "-", accuracy: 100}
move[600] = {id: 600, name_en: "Powder", type: type["Bug"], category: "Status", pp: 20, power: "-", accuracy: 100}
move[601] = {id: 601, name_en: "Geomancy", type: type["Fairy"], category: "Status", pp: 10, power: "-", accuracy: "-"}
move[602] = {id: 602, name_en: "Magnetic Flux", type: type["Electric"], category: "Status", pp: 20, power: "-", accuracy: "-"}
move[603] = {id: 603, name_en: "Happy Hour", type: type["Normal"], category: "Status", pp: 30, power: "-", accuracy: "-"}
move[604] = {id: 604, name_en: "Electric Terrain", type: type["Electric"], category: "Status", pp: 10, power: "-", accuracy: "-"}
move[605] = {id: 605, name_en: "Dazzling Gleam", type: type["Fairy"], category: "Special", pp: 10, power: 80, accuracy: 100}
move[606] = {id: 606, name_en: "Celebrate", type: type["Normal"], category: "Status", pp: 40, power: "-", accuracy: "-"}
move[607] = {id: 607, name_en: "Hold Hands", type: type["Normal"], category: "Status", pp: 40, power: "-", accuracy: "-"}
move[608] = {id: 608, name_en: "Baby-Doll Eyes", type: type["Fairy"], category: "Status", pp: 30, power: "-", accuracy: 100}
move[609] = {id: 609, name_en: "Nuzzle", type: type["Electric"], category: "Physical", pp: 20, power: 20, accuracy: 100}
move[610] = {id: 610, name_en: "Hold Back", type: type["Normal"], category: "Physical", pp: 40, power: 40, accuracy: 100}
move[611] = {id: 611, name_en: "Infestation", type: type["Bug"], category: "Special", pp: 20, power: 20, accuracy: 100}
move[612] = {id: 612, name_en: "Power-Up Punch", type: type["Fighting"], category: "Physical", pp: 20, power: 40, accuracy: 100}
move[613] = {id: 613, name_en: "Oblivion Wing", type: type["Flying"], category: "Special", pp: 10, power: 80, accuracy: 100}
move[614] = {id: 614, name_en: "Thousand Arrows", type: type["Ground"], category: "Physical", pp: 10, power: 90, accuracy: 100}
move[615] = {id: 615, name_en: "Thousand Waves", type: type["Ground"], category: "Physical", pp: 10, power: 90, accuracy: 100}
move[616] = {id: 616, name_en: "Land's Wrath", type: type["Ground"], category: "Physical", pp: 10, power: 90, accuracy: 100}
move[617] = {id: 617, name_en: "Light of Ruin", type: type["Fairy"], category: "Special", pp: 5, power: 140, accuracy: 90}
move[618] = {id: 618, name_en: "Origin Pulse", type: type["Water"], category: "Special", pp: 10, power: 110, accuracy: 85}
move[619] = {id: 619, name_en: "Precipice Blades", type: type["Ground"], category: "Physical", pp: 10, power: 120, accuracy: 85}
move[620] = {id: 620, name_en: "Dragon Ascent", type: type["Flying"], category: "Physical", pp: 5, power: 120, accuracy: 100}
move[621] = {id: 621, name_en: "Hyperspace Fury", type: type["Dark"], category: "Physical", pp: 5, power: 100, accuracy: "-"}

module.exports = move;